import { getLame } from '@shared/runtime/lame';
import { getTone } from '@shared/runtime/tone';
import { toolBySlug } from '@shared/tools';
import { bootstrapStandaloneTool } from '@shared/ui/standalone-tool';
import { t } from '@shared/i18n';
import './audio-rate.css';

void bootstrapStandaloneTool('audio-rate', (shell) => {
  if (!toolBySlug('audio-rate')) throw new Error('تعذر العثور على تعريف معدل الصوت.');
  shell.content.innerHTML = `
  <div class="arat-page">
    <header class="arat-header"><span class="arat-header-icon"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"/><path d="M19.07 4.93a10 10 0 0 1 0 14.14M15.54 8.46a5 5 0 0 1 0 7.07"/></svg></span><div><h1 class="arat-title">Slowed Studio</h1><p class="arat-sub">${t('تحكّم بسرعة الصوت وتأثيرات الصدى محلياً وبجودة احترافية.')}</p></div></header>
    <section class="arat-section"><p class="arat-section-label">${t('الملف الصوتي')}</p><label id="rate-drop-zone" class="arat-card arat-drop-zone" for="rate-file"><span class="arat-drop-icon"><svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/></svg></span><span id="rate-file-name" class="arat-drop-text">${t('اضغط هنا لرفع ملف صوتي (MP3 / WAV)')}</span><input id="rate-file" class="arat-file-input" type="file" accept="audio/*"></label></section>
    <section class="arat-section"><p class="arat-section-label">${t('التحكم بالسرعة')}</p><div class="arat-card arat-control-card"><div class="arat-ctrl-row"><span class="arat-ctrl-label">${t('السرعة والطبقة')}</span><strong id="speed-value" class="arat-ctrl-val">${t('طبيعي ({value}x)', { value: '1.00' })}</strong></div><input id="speed-slider" class="arat-slider" type="range" min="0.5" max="1.5" step="0.01" value="1" disabled><div class="arat-slider-marks"><span>0.5x</span><span>0.75x</span><span>1.0x</span><span>1.25x</span><span>1.5x</span></div><p id="speed-description" class="arat-speed-desc"></p></div></section>
    <section class="arat-section"><p class="arat-section-label">${t('تأثير الصدى')}</p><div class="arat-card arat-reverb-card"><div class="arat-reverb-header"><span class="arat-reverb-title"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"/><path d="M19 10v1a7 7 0 0 1-14 0v-1"/><line x1="12" y1="19" x2="12" y2="22"/></svg>${t('تأثير البيئة المحيطية (Reverb)')}</span><label class="arat-switch"><input id="reverb-toggle" type="checkbox" disabled><span class="arat-switch-knob"></span></label></div><div id="reverb-controls" class="arat-reverb-controls arat-disabled"><div class="arat-ctrl-row arat-sub-control"><span class="arat-ctrl-label">${t('زمن الاضمحلال (Decay)')}</span><strong id="decay-value" class="arat-ctrl-val">1.5s</strong></div><input id="decay-slider" class="arat-slider" type="range" min="0.5" max="8" step="0.1" value="1.5"><div class="arat-ctrl-row arat-sub-control"><span class="arat-ctrl-label">${t('مستوى المزج (Mix)')}</span><strong id="mix-value" class="arat-ctrl-val">30%</strong></div><input id="mix-slider" class="arat-slider" type="range" min="0" max="1" step="0.01" value="0.3"></div></div></section>
    <section class="arat-section"><button id="play-btn" class="arat-btn arat-btn-primary" type="button" disabled><svg id="play-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"/></svg><span id="play-copy">${t('تشغيل المعاينة')}</span></button></section>
    <section class="arat-section"><div id="rate-timeline" class="arat-timeline"><span id="current-time" class="arat-time">00:00</span><div id="rate-track" class="arat-progress-track"><i id="cut-fill" class="arat-cut-fill"></i><i id="progress-fill" class="arat-progress-fill"></i><i id="cut-start" class="arat-cut-thumb arat-cut-thumb-start"></i><i id="cut-end" class="arat-cut-thumb arat-cut-thumb-end"></i><i id="progress-thumb" class="arat-progress-thumb"></i></div><span id="total-time" class="arat-time">00:00</span></div><div id="cut-times" class="arat-cut-times" hidden><span id="cut-start-label" class="arat-cut-badge">${t('البداية:')} 00:00</span><span id="cut-duration-label" class="arat-cut-badge">${t('المدة:')} 00:00</span><span id="cut-end-label" class="arat-cut-badge">${t('النهاية:')} 00:00</span></div></section>
    <section id="export-progress" class="arat-section" hidden><div class="arat-card arat-worker-card"><div class="arat-ctrl-row"><span id="export-progress-label" class="arat-ctrl-label">${t('جاري المعالجة…')}</span><strong id="export-progress-value" class="arat-ctrl-val">0%</strong></div><div class="arat-progress-track arat-worker-track"><i id="export-progress-fill" class="arat-progress-fill"></i></div></div></section>
    <section class="arat-section"><p class="arat-section-label">${t('تصدير الملف')}</p><div class="arat-export-row"><button id="export-wav" class="arat-btn arat-btn-success" type="button" disabled><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg><span>${t('تصدير WAV بجودة غير مضغوطة')}</span></button><button id="export-mp3" class="arat-btn arat-btn-secondary" type="button" disabled><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg><span>${t('تصدير MP3 مضغوط')}</span></button></div></section>
    <section class="arat-section"><div class="arat-note-card"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/></svg><div><p class="arat-note-title">${t('لماذا ننصح بصيغة WAV؟')}</p><p class="arat-note-desc">${t('صيغة WAV غير مضغوطة وتحافظ على الترددات الصوتية الأصلية، ما يحافظ على عمق Bass ونقاء الصوت مع تأثيرات Slowed.')}</p></div></div></section>
  </div>`;

  const $ = <T extends Element>(selector: string) => required<T>(shell.content, selector);
  const input = $<HTMLInputElement>('#rate-file'), dropZone = $<HTMLElement>('#rate-drop-zone'), fileName = $<HTMLElement>('#rate-file-name');
  const speed = $<HTMLInputElement>('#speed-slider'), speedValue = $<HTMLElement>('#speed-value'), speedDescription = $<HTMLElement>('#speed-description');
  const reverb = $<HTMLInputElement>('#reverb-toggle'), controls = $<HTMLElement>('#reverb-controls'), decay = $<HTMLInputElement>('#decay-slider'), decayValue = $<HTMLElement>('#decay-value'), mix = $<HTMLInputElement>('#mix-slider'), mixValue = $<HTMLElement>('#mix-value');
  const play = $<HTMLButtonElement>('#play-btn'), playIcon = $<SVGElement>('#play-icon'), playCopy = $<HTMLElement>('#play-copy');
  const timeline = $<HTMLElement>('#rate-timeline'), track = $<HTMLElement>('#rate-track'), progressFill = $<HTMLElement>('#progress-fill'), progressThumb = $<HTMLElement>('#progress-thumb'), cutFill = $<HTMLElement>('#cut-fill'), startThumb = $<HTMLElement>('#cut-start'), endThumb = $<HTMLElement>('#cut-end'), currentTime = $<HTMLElement>('#current-time'), totalTime = $<HTMLElement>('#total-time'), cutTimes = $<HTMLElement>('#cut-times'), startLabel = $<HTMLElement>('#cut-start-label'), durationLabel = $<HTMLElement>('#cut-duration-label'), endLabel = $<HTMLElement>('#cut-end-label');
  const exportProgress = $<HTMLElement>('#export-progress'), exportLabel = $<HTMLElement>('#export-progress-label'), exportValue = $<HTMLElement>('#export-progress-value'), exportFill = $<HTMLElement>('#export-progress-fill'), wav = $<HTMLButtonElement>('#export-wav'), mp3 = $<HTMLButtonElement>('#export-mp3');

  let uploaded: File | null = null, buffer: AudioBuffer | null = null, tone: any = null, player: any = null, reverbNode: any = null, playing = false, position = 0, lastTime = 0, timelineTimer: number | null = null, cutStart = 0, cutEnd = 1, drag: 'start' | 'end' | 'seek' | null = null, resumeAfterSeek = false;
  const duration = () => buffer?.duration ?? 0, startAt = () => cutStart * duration(), endAt = () => cutEnd * duration(), playbackRate = () => Number(speed.value);
  const setProgress = (value: number, text: string) => { exportProgress.hidden = false; exportFill.style.width = `${value}%`; exportValue.textContent = `${Math.round(value)}%`; exportLabel.textContent = text; };
  const updateSpeed = () => { const value = playbackRate(); speedValue.textContent = Math.abs(value - 1) < .005 ? t('طبيعي ({value}x)', { value: '1.00' }) : `${value.toFixed(2)}x`; speedDescription.textContent = Math.abs(value - 1) < .005 ? '' : value < 1 ? t('إبطاء بمقدار {percent}% مع خفض الطبقة.', { percent: Math.round((1 - value) * 100) }) : t('تسريع بمقدار {percent}% مع رفع الطبقة.', { percent: Math.round((value - 1) * 100) }); };
  const updateCut = () => { const from = cutStart * 100, until = cutEnd * 100; startThumb.style.left = `${from}%`; endThumb.style.left = `${until}%`; cutFill.style.left = `${from}%`; cutFill.style.width = `${until - from}%`; startLabel.textContent = `${t('البداية:')} ${formatTime(startAt())}`; endLabel.textContent = `${t('النهاية:')} ${formatTime(endAt())}`; durationLabel.textContent = `${t('المدة:')} ${formatTime(endAt() - startAt())}`; };
  const updateTimeline = () => { const percent = duration() ? position / duration() : 0; progressFill.style.width = `${percent * 100}%`; progressThumb.style.left = `${percent * 100}%`; currentTime.textContent = formatTime(position); };

  const selectFile = async (file: File) => { uploaded = file; fileName.textContent = t('جاري قراءة الملف…'); try { tone = await getTone(); const decoded: AudioBuffer = await tone.getContext().decodeAudioData(await file.arrayBuffer()); buffer = decoded; player?.dispose(); reverbNode?.dispose(); reverbNode = new tone.Reverb({ decay: Number(decay.value), wet: 0 }).toDestination(); await reverbNode.generate(); player = new tone.Player(decoded).connect(reverbNode); fileName.textContent = file.name; totalTime.textContent = formatTime(decoded.duration); [speed, reverb, play, wav, mp3].forEach((element) => { element.disabled = false; }); cutTimes.hidden = false; position = 0; cutStart = 0; cutEnd = 1; updateSpeed(); syncReverb(); updateCut(); updateTimeline(); shell.setStatus(t('الملف جاهز. عدّل السرعة والقص والصدى ثم عاين أو صدّر.'), 'success'); } catch (error) { fileName.textContent = t('تعذر قراءة الملف'); shell.setStatus(t('تعذر قراءة الملف: {reason}', { reason: error instanceof Error ? error.message : t('خطأ غير متوقع') }), 'error'); } };
  input.addEventListener('change', () => { const file = input.files?.[0]; if (file) void selectFile(file); });
  ['dragenter', 'dragover'].forEach((name) => dropZone.addEventListener(name, (event) => { event.preventDefault(); dropZone.classList.add('drag-over'); }));
  ['dragleave', 'drop'].forEach((name) => dropZone.addEventListener(name, (event) => { event.preventDefault(); dropZone.classList.remove('drag-over'); }));
  dropZone.addEventListener('drop', (event) => { const file = event.dataTransfer?.files[0]; if (file) void selectFile(file); });
  speed.addEventListener('input', () => { updateSpeed(); if (player) { player.playbackRate = playbackRate(); if (playing) restartPreviewAtCurrentPosition(); } });
  reverb.addEventListener('change', syncReverb);
  decay.addEventListener('input', () => { decayValue.textContent = `${Number(decay.value).toFixed(1)}s`; });
  decay.addEventListener('change', async () => { if (reverbNode) { reverbNode.decay = Number(decay.value); await reverbNode.generate(); } });
  mix.addEventListener('input', () => { mixValue.textContent = `${Math.round(Number(mix.value) * 100)}%`; if (reverbNode && reverb.checked) setWetMix(Number(mix.value), .06); });

  function setWetMix(value: number, seconds: number): void { if (!reverbNode) return; if (typeof reverbNode.wet?.rampTo === 'function') reverbNode.wet.rampTo(value, seconds); else reverbNode.wet.value = value; }
  function syncReverb(): void { controls.classList.toggle('arat-disabled', !reverb.checked); if (!reverbNode) return; const target = reverb.checked ? Number(mix.value) : 0; const tail = reverb.checked ? .08 : Math.max(.35, Math.min(1.25, Number(decay.value) * .18)); setWetMix(target, tail); }
  function restartPreviewAtCurrentPosition(): void { if (!playing || !player || !tone || !buffer) return; const now = tone.now(); position = Math.min(endAt(), Math.max(startAt(), position + (now - lastTime) * player.playbackRate)); try { player.stop(now); } catch { /* لا يوجد مصدر نشط */ } player.playbackRate = playbackRate(); player.start(now + .02, position); lastTime = now + .02; updateTimeline(); }
  function stopTimeline(): void { if (timelineTimer !== null) window.clearInterval(timelineTimer); timelineTimer = null; }
  function startTimeline(): void { stopTimeline(); lastTime = tone.now(); timelineTimer = window.setInterval(() => { if (!playing || !buffer || !player) return; const now = tone.now(); position += (now - lastTime) * player.playbackRate; lastTime = now; if (position >= endAt() || position >= duration()) { position = startAt(); stop(false); updateTimeline(); return; } updateTimeline(); }, 100); }
  function stop(rememberPosition = true): void { if (rememberPosition && playing && tone && player) position = Math.min(endAt(), Math.max(startAt(), position)); try { player?.stop(); } catch { /* ليس قيد التشغيل */ } playing = false; stopTimeline(); playCopy.textContent = t('تشغيل المعاينة'); playIcon.innerHTML = '<polygon points="5 3 19 12 5 21 5 3"></polygon>'; play.style.background = 'var(--accent)'; }
  function start(): void { if (!buffer || !player || !tone) return; try { player.stop(); } catch { /* بداية أولى */ } position = startAt(); player.playbackRate = playbackRate(); player.start(0, position); lastTime = tone.now(); playing = true; playCopy.textContent = t('إيقاف'); playIcon.innerHTML = '<rect x="6" y="4" width="4" height="16"></rect><rect x="14" y="4" width="4" height="16"></rect>'; play.style.background = '#ff4b4b'; startTimeline(); }
  play.addEventListener('click', async () => { if (!tone) return; await tone.start(); playing ? stop() : start(); });

  const pointerPercent = (event: PointerEvent) => { const rect = track.getBoundingClientRect(); return Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)); };
  startThumb.addEventListener('pointerdown', (event) => { event.stopPropagation(); drag = 'start'; resumeAfterSeek = playing; startThumb.setPointerCapture(event.pointerId); });
  endThumb.addEventListener('pointerdown', (event) => { event.stopPropagation(); drag = 'end'; resumeAfterSeek = playing; endThumb.setPointerCapture(event.pointerId); });
  timeline.addEventListener('pointerdown', (event) => { if (!buffer || drag) return; drag = 'seek'; timeline.setPointerCapture(event.pointerId); resumeAfterSeek = playing; if (playing) { try { player?.stop(); } catch { /* لا شيء */ } stopTimeline(); } position = pointerPercent(event) * duration(); updateTimeline(); timeline.classList.add('scrubbing'); });
  timeline.addEventListener('pointermove', (event) => { if (!buffer || !drag) return; const percent = pointerPercent(event); if (drag === 'start') cutStart = Math.min(percent, cutEnd - .01); else if (drag === 'end') cutEnd = Math.max(percent, cutStart + .01); else position = percent * duration(); updateCut(); updateTimeline(); });
  const finishDrag = () => { const completed = drag; drag = null; timeline.classList.remove('scrubbing'); if (!buffer || !player || !tone || !resumeAfterSeek) { resumeAfterSeek = false; return; } try { player.stop(); } catch { /* لا شيء */ } position = completed === 'start' || completed === 'end' ? startAt() : position; player.playbackRate = playbackRate(); player.start(0, position); lastTime = tone.now(); playing = true; startTimeline(); resumeAfterSeek = false; }; timeline.addEventListener('pointerup', finishDrag); timeline.addEventListener('pointercancel', finishDrag);

  async function render(): Promise<AudioBuffer> { if (!buffer || !tone) throw new Error(t('لا يوجد ملف صوتي.')); const from = startAt(), until = endAt(), rate = playbackRate(), renderDuration = (until - from) / rate; return tone.Offline(async () => { const renderedReverb = new tone.Reverb({ decay: Number(decay.value), wet: reverb.checked ? Number(mix.value) : 0 }).toDestination(); await renderedReverb.generate(); const renderedPlayer = new tone.Player(buffer).connect(renderedReverb); renderedPlayer.playbackRate = rate; renderedPlayer.start(0, from); }, renderDuration); }
  const save = (blob: Blob, suffix: string) => { const url = URL.createObjectURL(blob), anchor = document.createElement('a'); anchor.href = url; anchor.download = `${uploaded?.name.replace(/\.[^.]+$/, '') || 'audio'}_${suffix}`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 800); };
  wav.addEventListener('click', async () => { wav.disabled = true; try { setProgress(8, t('يجري تصيير الصوت…')); const output = await render(); setProgress(75, t('يجري كتابة WAV…')); save(encodeWav(output), 'rate.wav'); setProgress(100, t('اكتمل تصدير WAV')); shell.setStatus(t('تم تنزيل ملف WAV محلياً.'), 'success'); } catch (error) { shell.setStatus(t('تعذر تصدير WAV: {reason}', { reason: error instanceof Error ? error.message : t('خطأ غير متوقع') }), 'error'); } finally { wav.disabled = false; window.setTimeout(() => { exportProgress.hidden = true; }, 1000); } });
  mp3.addEventListener('click', async () => { mp3.disabled = true; try { setProgress(8, t('يجري تصيير الصوت…')); const output = await render(); setProgress(50, t('جاري تحميل ترميز MP3…')); const result = await encodeMp3(output, (value) => setProgress(50 + value * .5, t('يجري ترميز MP3 ({percent}%)', { percent: value }))); save(result, 'rate.mp3'); setProgress(100, t('اكتمل تصدير MP3')); shell.setStatus(t('تم تنزيل ملف MP3 محلياً.'), 'success'); } catch (error) { shell.setStatus(t('تعذر تصدير MP3: {reason}', { reason: error instanceof Error ? error.message : t('خطأ غير متوقع') }), 'error'); } finally { mp3.disabled = false; window.setTimeout(() => { exportProgress.hidden = true; }, 1000); } });
});

async function encodeMp3(buffer: AudioBuffer, onProgress: (value: number) => void): Promise<Blob> {
  const lame = await getLame(); const encoder = new lame.Mp3Encoder(buffer.numberOfChannels, buffer.sampleRate, 192); const left = toInt16(buffer.getChannelData(0)); const right = buffer.numberOfChannels > 1 ? toInt16(buffer.getChannelData(1)) : left; const chunks: Int8Array[] = []; const block = 1152;
  for (let offset = 0; offset < left.length; offset += block) { const result = encoder.encodeBuffer(left.subarray(offset, offset + block), right.subarray(offset, offset + block)); if (result.length) chunks.push(result); if (offset % (block * 120) === 0) { onProgress(Math.round(offset / left.length * 100)); await new Promise<void>((resolve) => window.setTimeout(resolve, 0)); } }
  const final = encoder.flush(); if (final.length) chunks.push(final); onProgress(100); return new Blob(chunks.map((chunk) => chunk.buffer.slice(chunk.byteOffset, chunk.byteOffset + chunk.byteLength) as ArrayBuffer), { type: 'audio/mpeg' });
}
function encodeWav(buffer: AudioBuffer): Blob {
  const channels = buffer.numberOfChannels, frames = buffer.length, bytes = 44 + frames * channels * 2, data = new ArrayBuffer(bytes), view = new DataView(data); const write = (offset: number, text: string) => { for (let index = 0; index < text.length; index += 1) view.setUint8(offset + index, text.charCodeAt(index)); };
  write(0, 'RIFF'); view.setUint32(4, bytes - 8, true); write(8, 'WAVE'); write(12, 'fmt '); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, channels, true); view.setUint32(24, buffer.sampleRate, true); view.setUint32(28, buffer.sampleRate * channels * 2, true); view.setUint16(32, channels * 2, true); view.setUint16(34, 16, true); write(36, 'data'); view.setUint32(40, bytes - 44, true);
  const samples = Array.from({ length: channels }, (_, index) => buffer.getChannelData(index)); let offset = 44; for (let frame = 0; frame < frames; frame += 1) for (let channel = 0; channel < channels; channel += 1) { const sample = Math.max(-1, Math.min(1, samples[channel][frame])); view.setInt16(offset, sample < 0 ? sample * 0x8000 : sample * 0x7fff, true); offset += 2; } return new Blob([data], { type: 'audio/wav' });
}
function toInt16(source: Float32Array): Int16Array { const result = new Int16Array(source.length); source.forEach((value, index) => { const sample = Math.max(-1, Math.min(1, value)); result[index] = sample < 0 ? sample * 0x8000 : sample * 0x7fff; }); return result; }
function formatTime(seconds: number): string { const minutes = Math.floor(seconds / 60), remainder = Math.floor(seconds % 60); return `${String(minutes).padStart(2, '0')}:${String(remainder).padStart(2, '0')}`; }
function required<T extends Element>(root: ParentNode, selector: string): T { const element = root.querySelector<T>(selector); if (!element) throw new Error(`العنصر المطلوب غير موجود: ${selector}`); return element; }
