import JSZip from 'jszip';
import QRCode from 'qrcode';
import { getHtml5Qrcode, type Html5QrScanner } from '@shared/runtime/html5-qrcode';
import { bootstrapStandaloneTool } from '@shared/ui/standalone-tool';
import { toolBySlug } from '@shared/tools';
import { iconSvg } from '@shared/ui/icons';
import { t, getLocale } from '@shared/i18n';
import './local-share.css';

type ShareRole='host'|'guest';
type ShareState='idle'|'connecting'|'connected'|'transferring'|'completed'|'error';
type TransferMeta={type:'meta';name:string;size:number;mime:string};
type ControlMessage=TransferMeta|{type:'eof'}|{type:'cancel'};
type PendingFile={file:File;name:string};
type IncomingFile={name:string;size:number;mime:string;chunks:Uint8Array[];loaded:number;started:number};

void bootstrapStandaloneTool('local-share',(shell)=>{
  if(!toolBySlug('local-share'))throw new Error('تعذر العثور على تعريف أداة المشاركة المحلية.');
  shell.content.innerHTML=`<section class="local-share">
    <header class="ls-header">${iconSvg('share', 'ls-icon')}<div><h1>Arsenal Share Pro</h1><p>${t('نقل مباشر بين جهازين عبر WebRTC، مع تشفير DTLS تلقائي ومصافحة QR أو رمز يدوي.')}</p></div></header>
    <section id="ls-state-card" class="ls-card ls-state state-idle"><span class="ls-dot"></span><b id="ls-state-text">${t('جاهز لإنشاء جلسة آمنة')}</b><span class="ls-e2e">${iconSvg('lock', 'ls-inline-icon')}<em>E2E</em></span></section>
    <div id="ls-toast" class="ls-toast" aria-live="polite"></div>
    <section id="ls-setup"><div class="ls-tabs"><button id="ls-host-tab" class="active" type="button">${iconSvg('share', 'ls-inline-icon')} ${t('إرسال — إنشاء جلسة')}</button><button id="ls-guest-tab" type="button">${iconSvg('camera', 'ls-inline-icon')} ${t('استقبال — مسح QR')}</button></div>
      <section id="ls-host-panel" class="ls-panel active"><div class="ls-card"><button id="ls-start-host" class="ls-button primary" type="button">${iconSvg('qr', 'ls-inline-icon')} ${t('توليد رمز QR لجلسة الإرسال')}</button><div id="ls-host-step" class="ls-step" hidden><p>${t('1. اطلب من المستلم مسح هذا الرمز أو نسخ الرمز اليدوي.')}</p><div class="ls-qr"><canvas id="ls-host-canvas" width="280" height="280"></canvas></div><div class="ls-input-row"><input id="ls-host-offer" class="ls-input mono" readonly aria-label="${t('رمز العرض')}"><button id="ls-copy-offer" class="ls-icon-button" type="button" title="${t('نسخ الرمز')}">${iconSvg('copy', 'ls-inline-icon')}</button></div><p>${t('2. ألصق رمز ردّ المستلم هنا لإتمام الاتصال.')}</p><div class="ls-input-row"><input id="ls-host-answer" class="ls-input mono" placeholder="${t('ألصق رمز الرد هنا…')}"><button id="ls-accept-answer" class="ls-icon-button mint" type="button" title="${t('تأكيد الرد')}">${iconSvg('check', 'ls-inline-icon')}</button></div></div></div></section>
      <section id="ls-guest-panel" class="ls-panel"><div class="ls-card"><p>${t('1. امسح رمز QR الخاص بالمرسل أو ألصق رمز العرض يدوياً.')}</p><div id="ls-camera" class="ls-camera"><div id="ls-camera-region"></div><div class="ls-camera-target"></div></div><button id="ls-retry-camera" class="ls-text-button" type="button">${iconSvg('camera', 'ls-inline-icon')} ${t('فتح الكاميرا')}</button><p class="ls-or">— ${t('أو')} —</p><div class="ls-input-row"><input id="ls-guest-offer" class="ls-input mono" placeholder="${t('ألصق رمز المرسل هنا…')}"><button id="ls-accept-offer" class="ls-icon-button primary-outline" type="button" title="${t('قراءة رمز المرسل')}">${iconSvg('check', 'ls-inline-icon')}</button></div><div id="ls-guest-step" class="ls-step" hidden><p class="mint-text">${t('تمت القراءة. اطلب من المرسل مسح هذا الرد أو نسخه.')}</p><div class="ls-qr"><canvas id="ls-guest-canvas" width="280" height="280"></canvas></div><div class="ls-input-row"><input id="ls-guest-answer" class="ls-input mono" readonly aria-label="${t('رمز الرد')}"><button id="ls-copy-answer" class="ls-icon-button" type="button" title="${t('نسخ رمز الرد')}">${iconSvg('copy', 'ls-inline-icon')}</button></div></div></div></section>
    </section>
    <section id="ls-transfer" hidden><p class="ls-label">${t('الملفات')}</p><label id="ls-drop-zone" class="ls-drop-zone"><input id="ls-files" type="file" multiple hidden>${iconSvg('upload', 'ls-drop-icon')}<b>${t('اضغط أو اسحب الملفات أو المجلدات هنا للإرسال')}</b><small>${t('يُضغط اختيار الملفات المتعددة تلقائياً في ZIP قبل النقل.')}</small><span class="ls-file-actions"><span>${iconSvg('archive', 'ls-inline-icon')} ${t('ملفات متعددة')}</span><span id="ls-folder-label">${iconSvg('folder', 'ls-inline-icon')} ${t('مجلد كامل')}<input id="ls-folder" type="file" multiple webkitdirectory directory hidden></span></span></label>
      <section id="ls-preview" class="ls-card ls-preview" hidden><div><b id="ls-preview-name">—</b><small id="ls-preview-size">—</small></div><input id="ls-rename" class="ls-input" aria-label="${t('اسم الملف قبل الإرسال')}"><div class="ls-actions"><button id="ls-send" class="ls-button primary" type="button">${iconSvg('share', 'ls-inline-icon')} ${t('إرسال الآن')}</button><button id="ls-cancel-preview" class="ls-button ghost" type="button">${t('إلغاء')}</button></div></section>
      <section id="ls-progress-card" class="ls-card ls-progress-card" hidden><div class="ls-progress-header"><b id="ls-progress-name">${t('جاري المعالجة…')}</b><strong id="ls-progress-percent">0%</strong></div><div class="ls-progress"><span id="ls-progress-bar"></span></div><div class="ls-stat-grid"><span>${t('السرعة')} <b id="ls-speed">0 B/s</b></span><span>${t('المتبقي')} <b id="ls-eta">—</b></span><span>${t('النقل')} <b id="ls-transferred">0 / 0 B</b></span></div><button id="ls-cancel-transfer" class="ls-button danger" type="button">${iconSvg('close', 'ls-inline-icon')} ${t('إلغاء النقل')}</button></section>
      <p class="ls-label">${t('سجل العمليات')}</p><section id="ls-logs" class="ls-card ls-logs"><p>${t('بانتظار اتصال الجهاز الآخر…')}</p></section><button id="ls-disconnect" class="ls-button danger disconnect" type="button">${iconSvg('log-out', 'ls-inline-icon')} ${t('إنهاء الاتصال والمغادرة')}</button>
    </section>
  </section>`;
  const $=<T extends Element>(selector:string)=>required<T>(shell.content,selector);
  const hostTab=$<HTMLButtonElement>('#ls-host-tab'),guestTab=$<HTMLButtonElement>('#ls-guest-tab'),hostPanel=$<HTMLElement>('#ls-host-panel'),guestPanel=$<HTMLElement>('#ls-guest-panel');
  const stateCard=$<HTMLElement>('#ls-state-card'),stateText=$<HTMLElement>('#ls-state-text'),toast=$<HTMLElement>('#ls-toast'),setup=$<HTMLElement>('#ls-setup'),transfer=$<HTMLElement>('#ls-transfer');
  const hostStep=$<HTMLElement>('#ls-host-step'),guestStep=$<HTMLElement>('#ls-guest-step'),hostOffer=$<HTMLInputElement>('#ls-host-offer'),hostAnswer=$<HTMLInputElement>('#ls-host-answer'),guestOffer=$<HTMLInputElement>('#ls-guest-offer'),guestAnswer=$<HTMLInputElement>('#ls-guest-answer');
  const hostCanvas=$<HTMLCanvasElement>('#ls-host-canvas'),guestCanvas=$<HTMLCanvasElement>('#ls-guest-canvas'),camera=$<HTMLElement>('#ls-camera');
  const dropZone=$<HTMLElement>('#ls-drop-zone'),filesInput=$<HTMLInputElement>('#ls-files'),folderInput=$<HTMLInputElement>('#ls-folder'),preview=$<HTMLElement>('#ls-preview'),previewName=$<HTMLElement>('#ls-preview-name'),previewSize=$<HTMLElement>('#ls-preview-size'),rename=$<HTMLInputElement>('#ls-rename');
  const progressCard=$<HTMLElement>('#ls-progress-card'),progressName=$<HTMLElement>('#ls-progress-name'),progressPercent=$<HTMLElement>('#ls-progress-percent'),progressBar=$<HTMLElement>('#ls-progress-bar'),speed=$<HTMLElement>('#ls-speed'),eta=$<HTMLElement>('#ls-eta'),transferred=$<HTMLElement>('#ls-transferred'),logs=$<HTMLElement>('#ls-logs');
  let state:ShareState='idle',pc:RTCPeerConnection|undefined,channel:RTCDataChannel|undefined,scanner:Html5QrScanner|undefined,cameraRequest=0,pending:PendingFile|undefined,incoming:IncomingFile|undefined,abortController:AbortController|undefined;
  const statusText:Record<ShareState,string>={idle:t('جاهز لإنشاء جلسة آمنة'),connecting:t('يجري إنشاء اتصال آمن…'),connected:t('تم الاتصال بالجهاز الآخر'),transferring:t('يجري نقل الملف محلياً…'),completed:t('اكتمل النقل بنجاح'),error:t('تعذر إكمال الاتصال أو النقل')};
  const log=(message:string,kind:'info'|'success'|'error'|'warn'='info')=>{const row=document.createElement('p');row.className=`ls-log ${kind}`;row.textContent=`[${new Date().toLocaleTimeString(getLocale())}] ${message}`;if(logs.firstElementChild?.textContent===t('بانتظار اتصال الجهاز الآخر…'))logs.replaceChildren();logs.prepend(row);};
  const notify=(message:string,kind:'info'|'success'|'error'|'warn'='info')=>{const note=document.createElement('div');note.className=`ls-toast-item ${kind}`;note.textContent=message;toast.append(note);setTimeout(()=>note.remove(),3600);};
  const setState=(next:ShareState,message?:string)=>{state=next;stateCard.className=`ls-card ls-state state-${next}`;stateText.textContent=message||statusText[next];shell.setStatus(message||statusText[next],next==='error'?'error':next==='completed'||next==='connected'?'success':undefined);};
  const setTab=(next:ShareRole)=>{const hosting=next==='host';hostTab.classList.toggle('active',hosting);guestTab.classList.toggle('active',!hosting);hostPanel.classList.toggle('active',hosting);guestPanel.classList.toggle('active',!hosting);if(hosting)stopCamera();else void startCamera();};
  const cleanupCamera=()=>{cameraRequest+=1;const current=scanner;scanner=undefined;if(current)void current.stop().then(()=>current.clear()).catch(()=>undefined);camera.innerHTML='<div id="ls-camera-region"></div><div class="ls-camera-target"></div>';};
  const stopCamera=()=>cleanupCamera();
  const startCamera=async()=>{stopCamera();const request=++cameraRequest;try{const Scanner=await getHtml5Qrcode();if(request!==cameraRequest)return;const active=new Scanner('ls-camera-region');scanner=active;await active.start({facingMode:'environment'},{fps:10,qrbox:{width:220,height:220}},(decoded)=>{if(request!==cameraRequest)return;guestOffer.value=decoded;notify(t('تمت قراءة رمز المرسل.'),'success');log(t('تمت قراءة رمز العرض من QR.'),'success');stopCamera();},()=>undefined);}catch{if(request!==cameraRequest)return;stopCamera();camera.innerHTML=`<p class="ls-camera-error">${t('تعذر فتح الكاميرا. استخدم لصق الرمز اليدوي.')}</p>`;notify(t('تعذر فتح الكاميرا؛ يمكنك لصق رمز المرسل يدوياً.'),'warn');}};
  const drawQr=async(canvas:HTMLCanvasElement,code:string)=>{await QRCode.toCanvas(canvas,code,{width:280,margin:2,errorCorrectionLevel:'L',color:{dark:'#000000',light:'#ffffff'}});};
  const closeConnection=(resetUi=true)=>{abortController?.abort();abortController=undefined;pending=undefined;incoming=undefined;channel?.close();pc?.close();channel=undefined;pc=undefined;stopCamera();if(resetUi){setup.hidden=false;transfer.hidden=true;hostStep.hidden=true;guestStep.hidden=true;preview.hidden=true;progressCard.hidden=true;hostOffer.value='';hostAnswer.value='';guestOffer.value='';guestAnswer.value='';logs.innerHTML=`<p>${t('بانتظار اتصال الجهاز الآخر…')}</p>`;setState('idle');}};
  const createPc=()=>{closeConnection(false);if(!('RTCPeerConnection' in window))throw new Error(t('متصفحك لا يدعم WebRTC.'));const connection=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pc=connection;connection.onconnectionstatechange=()=>{if(connection!==pc)return;const value=connection.connectionState;if(value==='connected'){setState('connected');setup.hidden=true;transfer.hidden=false;log(t('تم إنشاء اتصال P2P مشفّر بين الجهازين.'),'success');}else if(value==='failed'||value==='disconnected'){setState('error',t('فُقد اتصال الجهاز الآخر.'));log(t('فُقد الاتصال أو تعذر تأسيسه.'),'error');}};return connection;};
  const bindChannel=(next:RTCDataChannel)=>{channel=next;next.binaryType='arraybuffer';next.bufferedAmountLowThreshold=512*1024;next.onopen=()=>{setState('connected');setup.hidden=true;transfer.hidden=false;notify(t('تم الاتصال بالجهاز الآخر.'),'success');};next.onclose=()=>{if(state!=='idle')setState('error',t('أغلق الجهاز الآخر قناة النقل.'));};next.onmessage=(event)=>void handleIncoming(event.data);};
  const startHost=async()=>{try{const connection=createPc();setState('connecting',t('يجري إعداد جلسة الإرسال…'));const data=connection.createDataChannel('arsenal-transfer');bindChannel(data);const offer=await connection.createOffer();await connection.setLocalDescription(offer);const code=await waitAndEncode(connection);hostOffer.value=code;await drawQr(hostCanvas,code);hostStep.hidden=false;setState('connecting',t('بانتظار رمز رد المستلم…'));log(t('تم إنشاء رمز العرض. أرسله إلى الجهاز المستلم.'),'success');notify(t('تم إنشاء رمز QR ورمز جلسة الإرسال.'),'success');}catch(error){setState('error',errorMessage(error));notify(errorMessage(error),'error');}};
  const acceptAnswer=async()=>{if(!pc){notify(t('أنشئ جلسة إرسال أولاً.'),'error');return;}const value=hostAnswer.value.trim();if(!value){notify(t('ألصق رمز الرد أولاً.'),'error');return;}try{await pc.setRemoteDescription(await decodeSignal(value));setState('connecting',t('تم قبول الرد؛ يجري الاتصال بالجهاز الآخر…'));log(t('قُبل رمز الرد بانتظار فتح قناة النقل.'));}catch{setState('error',t('رمز الرد غير صالح.'));notify(t('تعذر قراءة رمز الرد.'),'error');}};
  const acceptOffer=async()=>{const value=guestOffer.value.trim();if(!value){notify(t('ألصق رمز المرسل أو امسح QR أولاً.'),'error');return;}try{const connection=createPc();setState('connecting',t('يجري قبول جلسة المرسل…'));connection.ondatachannel=(event)=>bindChannel(event.channel);await connection.setRemoteDescription(await decodeSignal(value));const answer=await connection.createAnswer();await connection.setLocalDescription(answer);const code=await waitAndEncode(connection);guestAnswer.value=code;await drawQr(guestCanvas,code);guestStep.hidden=false;setState('connecting',t('بانتظار المرسل لتأكيد رمز الرد…'));stopCamera();log(t('تم إنشاء رمز الرد. أرسله إلى المرسل.'),'success');notify(t('تم إنشاء رمز QR ورمز الرد.'),'success');}catch{setState('error',t('رمز المرسل غير صالح أو تالف.'));notify(t('تعذر قراءة رمز المرسل.'),'error');}};
  const prepareFiles=async(list:File[])=>{if(!list.length)return;if(channel?.readyState!=='open'){notify(t('انتظر اكتمال اتصال الجهاز الآخر قبل اختيار الملفات.'),'error');return;}try{let file:File;if(list.length===1&&!list[0].webkitRelativePath)file=list[0];else{log(t('يجري ضغط الملفات قبل نقلها…'));const zip=new JSZip();for(const item of list)zip.file(item.webkitRelativePath||item.name,item);const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:3}});file=new File([blob],'Arsenal_Archive.zip',{type:'application/zip'});}if(!file.size)throw new Error(t('لا يمكن نقل ملف فارغ.'));pending={file,name:file.name};previewName.textContent=file.name;previewSize.textContent=formatBytes(file.size);rename.value=file.name;preview.hidden=false;log(t('تم تجهيز {name} للإرسال.', { name: file.name }));}catch(error){notify(errorMessage(error),'error');log(errorMessage(error),'error');}};
  const updateProgress=(loaded:number,total:number,started:number,name:string)=>{const elapsed=Math.max((performance.now()-started)/1000,.01),rate=loaded/elapsed,percent=total?loaded/total*100:0,remaining=rate?(total-loaded)/rate:Infinity;progressCard.hidden=false;progressName.textContent=name;progressPercent.textContent=`${percent.toFixed(1)}%`;progressBar.style.width=`${percent}%`;speed.textContent=`${formatBytes(rate)}/s`;eta.textContent=Number.isFinite(remaining)?t('{count} ث', { count: Math.ceil(remaining) }):'—';transferred.textContent=`${formatBytes(loaded)} / ${formatBytes(total)}`;};
  const sendPending=async()=>{if(!pending||channel?.readyState!=='open'){notify(t('قناة النقل غير جاهزة.'),'error');return;}const nextFile=pending.file,outputName=rename.value.trim()||nextFile.name,file=outputName===nextFile.name?nextFile:new File([nextFile],outputName,{type:nextFile.type});preview.hidden=true;abortController=new AbortController();setState('transferring');try{const buffer=await file.arrayBuffer(),chunkSize=64*1024,started=performance.now();channel.send(JSON.stringify({type:'meta',name:file.name,size:buffer.byteLength,mime:file.type} satisfies TransferMeta));for(let offset=0;offset<buffer.byteLength;offset+=chunkSize){if(abortController.signal.aborted)throw new Error(t('أُلغي النقل.'));while(channel.bufferedAmount>channel.bufferedAmountLowThreshold)await waitForBuffer(channel,abortController.signal);const chunk=buffer.slice(offset,Math.min(offset+chunkSize,buffer.byteLength));channel.send(chunk);updateProgress(Math.min(offset+chunk.byteLength,buffer.byteLength),buffer.byteLength,started,file.name);}channel.send(JSON.stringify({type:'eof'} satisfies ControlMessage));updateProgress(buffer.byteLength,buffer.byteLength,started,file.name);setState('completed',t('اكتمل إرسال {name}', { name: file.name }));notify(t('تم إرسال {name} بنجاح.', { name: file.name }),'success');log(t('اكتمل إرسال {name}.', { name: file.name }),'success');}catch(error){if(channel.readyState==='open')channel.send(JSON.stringify({type:'cancel'} satisfies ControlMessage));setState('error',errorMessage(error));notify(errorMessage(error),'error');log(errorMessage(error),'error');}finally{pending=undefined;abortController=undefined;setTimeout(()=>{progressCard.hidden=true;if(state==='completed')setState('connected');},3000);}};
  const handleIncoming=async(data:unknown)=>{if(typeof data==='string'){let message:ControlMessage;try{message=JSON.parse(data) as ControlMessage;}catch{return;}if(message.type==='meta'){incoming={name:message.name,size:message.size,mime:message.mime,chunks:[],loaded:0,started:performance.now()};setState('transferring',t('يجري استقبال {name}', { name: message.name }));log(t('بدأ استقبال {name}.', { name: message.name }));return;}if(message.type==='cancel'){incoming=undefined;progressCard.hidden=true;setState('connected');notify(t('ألغى الجهاز الآخر النقل.'),'warn');log(t('ألغى الجهاز الآخر النقل.'),'warn');return;}if(message.type==='eof'&&incoming){const completed=incoming;const blob=new Blob(completed.chunks.map(toArrayBuffer),{type:completed.mime||'application/octet-stream'});download(blob,completed.name);updateProgress(completed.loaded,completed.size,completed.started,completed.name);incoming=undefined;setState('completed',t('اكتمل استقبال {name}', { name: completed.name }));notify(t('تم استلام {name}.', { name: completed.name }),'success');log(t('اكتمل استقبال {name}.', { name: completed.name }),'success');setTimeout(()=>{progressCard.hidden=true;if(state==='completed')setState('connected');},3000);return;}}if(incoming&&data instanceof ArrayBuffer){const chunk=new Uint8Array(data);incoming.chunks.push(chunk);incoming.loaded+=chunk.byteLength;updateProgress(incoming.loaded,incoming.size,incoming.started,incoming.name);}};
  const drop=(event:DragEvent)=>{event.preventDefault();dropZone.classList.remove('dragover');if(event.dataTransfer)void prepareFiles([...event.dataTransfer.files]);};

  hostTab.addEventListener('click',()=>setTab('host'));guestTab.addEventListener('click',()=>setTab('guest'));$('#ls-start-host').addEventListener('click',()=>void startHost());$('#ls-accept-answer').addEventListener('click',()=>void acceptAnswer());$('#ls-accept-offer').addEventListener('click',()=>void acceptOffer());$('#ls-retry-camera').addEventListener('click',()=>void startCamera());
  $('#ls-copy-offer').addEventListener('click',()=>void copyText(hostOffer.value,t('تم نسخ رمز العرض.')));$('#ls-copy-answer').addEventListener('click',()=>void copyText(guestAnswer.value,t('تم نسخ رمز الرد.')));
  filesInput.addEventListener('change',()=>void prepareFiles([...(filesInput.files??[])]));folderInput.addEventListener('change',()=>void prepareFiles([...(folderInput.files??[])]));dropZone.addEventListener('dragover',(event)=>{event.preventDefault();dropZone.classList.add('dragover');});dropZone.addEventListener('dragleave',()=>dropZone.classList.remove('dragover'));dropZone.addEventListener('drop',drop);$('#ls-cancel-preview').addEventListener('click',()=>{pending=undefined;preview.hidden=true;});$('#ls-send').addEventListener('click',()=>void sendPending());$('#ls-cancel-transfer').addEventListener('click',()=>abortController?.abort());$('#ls-disconnect').addEventListener('click',()=>{closeConnection();log(t('أُغلقت الجلسة محلياً.'));});
  window.addEventListener('pagehide',()=>closeConnection(false),{once:true});

  async function copyText(value:string,message:string){if(!value){notify(t('لا يوجد رمز لنسخه.'),'error');return;}try{await navigator.clipboard.writeText(value);notify(message,'success');log(message,'success');}catch{notify(t('تعذر النسخ تلقائياً. انسخ الرمز يدوياً.'),'error');}}
});

async function waitAndEncode(connection:RTCPeerConnection):Promise<string>{await waitIce(connection,3000);if(!connection.localDescription)throw new Error(t('تعذر إنشاء وصف الاتصال.'));return encodeSignal(connection.localDescription);}
async function encodeSignal(description:RTCSessionDescriptionInit):Promise<string>{const json=JSON.stringify(description);if('CompressionStream' in window){const stream=new CompressionStream('deflate-raw'),writer=stream.writable.getWriter(),read=new Response(stream.readable).arrayBuffer();await writer.write(new TextEncoder().encode(json));await writer.close();return bytesToBase64(new Uint8Array(await read));}return `raw.${bytesToBase64(new TextEncoder().encode(json))}`;}
async function decodeSignal(code:string):Promise<RTCSessionDescriptionInit>{const value=code.trim();if(!value)throw new Error(t('رمز الاتصال فارغ.'));try{let json:string;if(value.startsWith('raw.'))json=new TextDecoder().decode(base64ToBytes(value.slice(4)));else if('DecompressionStream' in window){const stream=new DecompressionStream('deflate-raw'),writer=stream.writable.getWriter(),read=new Response(stream.readable).arrayBuffer();await writer.write(toArrayBuffer(base64ToBytes(value)));await writer.close();json=new TextDecoder().decode(await read);}else throw new Error();const parsed=JSON.parse(json) as RTCSessionDescriptionInit;if(!parsed.type||!parsed.sdp)throw new Error();return parsed;}catch{throw new Error(t('رمز الاتصال غير صالح أو غير مكتمل.'));}}
function toArrayBuffer(bytes:Uint8Array):ArrayBuffer{return bytes.slice().buffer as ArrayBuffer;}
function bytesToBase64(bytes:Uint8Array):string{let result='';for(let offset=0;offset<bytes.length;offset+=0x8000)result+=String.fromCharCode(...bytes.subarray(offset,offset+0x8000));return btoa(result);}
function base64ToBytes(value:string):Uint8Array{const source=atob(value),bytes=new Uint8Array(source.length);for(let index=0;index<source.length;index+=1)bytes[index]=source.charCodeAt(index);return bytes;}
function waitIce(connection:RTCPeerConnection,timeout:number):Promise<void>{return new Promise((resolve)=>{if(connection.iceGatheringState==='complete'){resolve();return;}const timer=window.setTimeout(resolve,timeout);const check=()=>{if(connection.iceGatheringState==='complete'){clearTimeout(timer);connection.removeEventListener('icegatheringstatechange',check);resolve();}};connection.addEventListener('icegatheringstatechange',check);});}
function waitForBuffer(channel:RTCDataChannel,signal:AbortSignal):Promise<void>{return new Promise((resolve,reject)=>{const complete=()=>{channel.removeEventListener('bufferedamountlow',complete);signal.removeEventListener('abort',aborted);resolve();};const aborted=()=>{channel.removeEventListener('bufferedamountlow',complete);reject(new Error(t('أُلغي النقل.')));};channel.addEventListener('bufferedamountlow',complete,{once:true});signal.addEventListener('abort',aborted,{once:true});});}
function download(blob:Blob,name:string):void{const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();setTimeout(()=>{link.remove();URL.revokeObjectURL(url);},160);}
function formatBytes(bytes:number):string{if(!bytes)return '0 B';const units=['B','KB','MB','GB'],power=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);return `${(bytes/1024**power).toFixed(power?2:0)} ${units[power]}`;}
function errorMessage(error:unknown):string{return error instanceof Error?error.message:t('حدث خطأ غير متوقع.');}
function required<T extends Element>(root:ParentNode,selector:string):T{const element=root.querySelector<T>(selector);if(!element)throw new Error(`العنصر المطلوب غير موجود: ${selector}`);return element;}
