type VideoToAudioTranslationRow = Record<string, string>;

/** نصوص محول الفيديو إلى صوت، مراجعة يدوياً مع إبقاء WAV وMP3 أسماء صيغ تقنية. */
export const reviewedVideoToAudioText: Record<string, VideoToAudioTranslationRow> = {
  'مستخرج الصوت من الفيديو': { en: 'Video Audio Extractor', es: 'Extractor de audio de vídeo', fr: 'Extracteur audio de vidéo', de: 'Video-Audio-Extraktor', tr: 'Video Ses Çıkarıcı', ru: 'Извлечение аудио из видео', hi: 'वीडियो ऑडियो एक्सट्रैक्टर', zh: '视频音频提取器' },
  'استخراج المسار الصوتي من أي فيديو وتحويله إلى WAV أو MP3 — محلياً وبدون إنترنت.': { en: 'Extract the audio track from any video and convert it to WAV or MP3 — locally and offline.', es: 'Extrae la pista de audio de cualquier vídeo y conviértela a WAV o MP3, de forma local y sin conexión.', fr: 'Extrayez la piste audio de n’importe quelle vidéo et convertissez-la en WAV ou MP3, localement et hors ligne.', de: 'Extrahieren Sie die Audiospur aus jedem Video und konvertieren Sie sie lokal und offline in WAV oder MP3.', tr: 'Herhangi bir videodan ses parçasını çıkarın ve yerel olarak, çevrimdışı WAV veya MP3’e dönüştürün.', ru: 'Извлекайте аудиодорожку из любого видео и конвертируйте её в WAV или MP3 — локально и без интернета.', hi: 'किसी भी वीडियो से ऑडियो ट्रैक निकालें और उसे WAV या MP3 में बदलें — स्थानीय रूप से और ऑफ़लाइन।', zh: '从任意视频中提取音轨，并在本地离线转换为 WAV 或 MP3。' },
  'ملف الفيديو': { en: 'Video file', es: 'Archivo de vídeo', fr: 'Fichier vidéo', de: 'Videodatei', tr: 'Video dosyası', ru: 'Видеофайл', hi: 'वीडियो फ़ाइल', zh: '视频文件' },
  'اضغط هنا لاختيار ملف الفيديو': { en: 'Click here to choose a video file', es: 'Haz clic aquí para elegir un archivo de vídeo', fr: 'Cliquez ici pour choisir un fichier vidéo', de: 'Hier klicken, um eine Videodatei auszuwählen', tr: 'Bir video dosyası seçmek için buraya tıklayın', ru: 'Нажмите здесь, чтобы выбрать видеофайл', hi: 'वीडियो फ़ाइल चुनने के लिए यहाँ क्लिक करें', zh: '点击此处选择视频文件' },
  'يدعم MP4 وWebM وMOV وغيرها': { en: 'Supports MP4, WebM, MOV, and more', es: 'Compatible con MP4, WebM, MOV y más', fr: 'Compatible avec MP4, WebM, MOV et plus encore', de: 'Unterstützt MP4, WebM, MOV und mehr', tr: 'MP4, WebM, MOV ve daha fazlasını destekler', ru: 'Поддерживаются MP4, WebM, MOV и другие форматы', hi: 'MP4, WebM, MOV और अन्य समर्थित हैं', zh: '支持 MP4、WebM、MOV 等格式' },
  'جاري المعالجة…': { en: 'Processing…', es: 'Procesando…', fr: 'Traitement…', de: 'Verarbeitung…', tr: 'İşleniyor…', ru: 'Обработка…', hi: 'प्रोसेस हो रहा है…', zh: '正在处理…' },
  'حجم الفيديو': { en: 'Video size', es: 'Tamaño del vídeo', fr: 'Taille de la vidéo', de: 'Videogröße', tr: 'Video boyutu', ru: 'Размер видео', hi: 'वीडियो आकार', zh: '视频大小' },
  'حجم الصوت المستخرج': { en: 'Extracted audio size', es: 'Tamaño del audio extraído', fr: 'Taille de l’audio extrait', de: 'Größe des extrahierten Audios', tr: 'Çıkarılan ses boyutu', ru: 'Размер извлечённого аудио', hi: 'निकाले गए ऑडियो का आकार', zh: '提取的音频大小' },
  'تشغيل المعاينة': { en: 'Play preview', es: 'Reproducir vista previa', fr: 'Lire l’aperçu', de: 'Vorschau abspielen', tr: 'Önizlemeyi oynat', ru: 'Воспроизвести предпросмотр', hi: 'प्रीव्यू चलाएँ', zh: '播放预览' },
  'إيقاف': { en: 'Stop', es: 'Detener', fr: 'Arrêter', de: 'Anhalten', tr: 'Durdur', ru: 'Остановить', hi: 'रोकें', zh: '停止' },
  'صيغة التصدير': { en: 'Export format', es: 'Formato de exportación', fr: 'Format d’exportation', de: 'Exportformat', tr: 'Dışa aktarma biçimi', ru: 'Формат экспорта', hi: 'एक्सपोर्ट फ़ॉर्मेट', zh: '导出格式' },
  'خام ونقي 100٪': { en: 'Raw, lossless quality', es: 'Calidad sin pérdidas', fr: 'Qualité brute sans perte', de: 'Roh, verlustfreie Qualität', tr: 'Ham, kayıpsız kalite', ru: 'Без потерь, исходное качество', hi: 'रॉ, लॉसलेस गुणवत्ता', zh: '原始无损质量' },
  'مضغوط وعالي التوافق': { en: 'Compressed and highly compatible', es: 'Comprimido y muy compatible', fr: 'Compressé et très compatible', de: 'Komprimiert und sehr kompatibel', tr: 'Sıkıştırılmış ve yüksek uyumlu', ru: 'Сжатый и широко совместимый', hi: 'कंप्रेस्ड और अत्यधिक संगत', zh: '已压缩且兼容性高' },
  'تحميل ملف الصوت ({format})': { en: 'Download audio file ({format})', es: 'Descargar archivo de audio ({format})', fr: 'Télécharger le fichier audio ({format})', de: 'Audiodatei herunterladen ({format})', tr: 'Ses dosyasını indir ({format})', ru: 'Скачать аудиофайл ({format})', hi: 'ऑडियो फ़ाइल डाउनलोड करें ({format})', zh: '下载音频文件 ({format})' },
  'جاري قراءة المسار الصوتي…': { en: 'Reading audio track…', es: 'Leyendo la pista de audio…', fr: 'Lecture de la piste audio…', de: 'Audiospur wird gelesen…', tr: 'Ses parçası okunuyor…', ru: 'Чтение аудиодорожки…', hi: 'ऑडियो ट्रैक पढ़ा जा रहा है…', zh: '正在读取音轨…' },
  'جاري قراءة الفيديو…': { en: 'Reading video…', es: 'Leyendo el vídeo…', fr: 'Lecture de la vidéo…', de: 'Video wird gelesen…', tr: 'Video okunuyor…', ru: 'Чтение видео…', hi: 'वीडियो पढ़ा जा रहा है…', zh: '正在读取视频…' },
  'جاري فك ترميز المسار الصوتي…': { en: 'Decoding audio track…', es: 'Decodificando la pista de audio…', fr: 'Décodage de la piste audio…', de: 'Audiospur wird decodiert…', tr: 'Ses parçası çözümleniyor…', ru: 'Декодирование аудиодорожки…', hi: 'ऑडियो ट्रैक डिकोड हो रहा है…', zh: '正在解码音轨…' },
  'يجري إنشاء WAV…': { en: 'Creating WAV…', es: 'Creando WAV…', fr: 'Création du WAV…', de: 'WAV wird erstellt…', tr: 'WAV oluşturuluyor…', ru: 'Создание WAV…', hi: 'WAV बनाया जा रहा है…', zh: '正在创建 WAV…' },
  'اكتمل استخراج المسار الصوتي': { en: 'Audio extraction complete', es: 'Extracción de audio completada', fr: 'Extraction audio terminée', de: 'Audioextraktion abgeschlossen', tr: 'Ses çıkarma tamamlandı', ru: 'Извлечение аудио завершено', hi: 'ऑडियो एक्सट्रैक्शन पूरा हुआ', zh: '音频提取完成' },
  'تم استخراج الصوت محلياً. يمكنك معاينته أو تنزيله بصيغة WAV أو MP3.': { en: 'Audio was extracted locally. You can preview it or download it as WAV or MP3.', es: 'El audio se extrajo localmente. Puedes previsualizarlo o descargarlo como WAV o MP3.', fr: 'L’audio a été extrait localement. Vous pouvez l’écouter ou le télécharger en WAV ou MP3.', de: 'Audio wurde lokal extrahiert. Sie können es anhören oder als WAV bzw. MP3 herunterladen.', tr: 'Ses yerel olarak çıkarıldı. Önizleyebilir veya WAV ya da MP3 olarak indirebilirsiniz.', ru: 'Аудио извлечено локально. Его можно прослушать или скачать в WAV либо MP3.', hi: 'ऑडियो स्थानीय रूप से निकाला गया। आप इसका प्रीव्यू कर सकते हैं या WAV अथवा MP3 में डाउनलोड कर सकते हैं।', zh: '音频已在本地提取。您可以预览或下载为 WAV 或 MP3。' },
  'تعذر استخراج صوت من هذا الفيديو': { en: 'Could not extract audio from this video', es: 'No se pudo extraer el audio de este vídeo', fr: 'Impossible d’extraire l’audio de cette vidéo', de: 'Audio konnte nicht aus diesem Video extrahiert werden', tr: 'Bu videodan ses çıkarılamadı', ru: 'Не удалось извлечь аудио из этого видео', hi: 'इस वीडियो से ऑडियो नहीं निकाला जा सका', zh: '无法从此视频中提取音频' },
  'تعذر استخراج الصوت: {reason}': { en: 'Could not extract audio: {reason}', es: 'No se pudo extraer el audio: {reason}', fr: 'Impossible d’extraire l’audio : {reason}', de: 'Audio konnte nicht extrahiert werden: {reason}', tr: 'Ses çıkarılamadı: {reason}', ru: 'Не удалось извлечь аудио: {reason}', hi: 'ऑडियो नहीं निकाला जा सका: {reason}', zh: '无法提取音频：{reason}' },
  'جاري تحميل ترميز MP3…': { en: 'Loading MP3 encoder…', es: 'Cargando el codificador MP3…', fr: 'Chargement de l’encodeur MP3…', de: 'MP3-Encoder wird geladen…', tr: 'MP3 kodlayıcı yükleniyor…', ru: 'Загрузка MP3-кодировщика…', hi: 'MP3 एन्कोडर लोड हो रहा है…', zh: '正在加载 MP3 编码器…' },
  'يجري ترميز MP3: {percent}%': { en: 'Encoding MP3: {percent}%', es: 'Codificando MP3: {percent}%', fr: 'Encodage MP3 : {percent} %', de: 'MP3 wird kodiert: {percent} %', tr: 'MP3 kodlanıyor: %{percent}', ru: 'Кодирование MP3: {percent}%', hi: 'MP3 एन्कोड हो रहा है: {percent}%', zh: '正在编码 MP3：{percent}%' },
  'تم تنزيل ملف الصوت محلياً.': { en: 'Audio file downloaded locally.', es: 'El archivo de audio se descargó localmente.', fr: 'Le fichier audio a été téléchargé localement.', de: 'Audiodatei wurde lokal heruntergeladen.', tr: 'Ses dosyası yerel olarak indirildi.', ru: 'Аудиофайл скачан локально.', hi: 'ऑडियो फ़ाइल स्थानीय रूप से डाउनलोड हो गई।', zh: '音频文件已在本地下载。' },
  'تعذر إنشاء MP3: {reason}': { en: 'Could not create MP3: {reason}', es: 'No se pudo crear el MP3: {reason}', fr: 'Impossible de créer le MP3 : {reason}', de: 'MP3 konnte nicht erstellt werden: {reason}', tr: 'MP3 oluşturulamadı: {reason}', ru: 'Не удалось создать MP3: {reason}', hi: 'MP3 नहीं बनाया जा सका: {reason}', zh: '无法创建 MP3：{reason}' },
  'خطأ غير متوقع': { en: 'Unexpected error', es: 'Error inesperado', fr: 'Erreur inattendue', de: 'Unerwarteter Fehler', tr: 'Beklenmeyen hata', ru: 'Непредвиденная ошибка', hi: 'अनपेक्षित त्रुटि', zh: '意外错误' }
};
