type SettingsTranslationRow = Record<string, string>;

/** نصوص الإعدادات الأعلى ظهوراً، مراجعة يدوياً قبل عرضها للمستخدم. */
export const reviewedSettingsText: Record<string, SettingsTranslationRow> = {
  'تحكم في تجربتك داخل الترسانة.': { en: 'Control your Arsenal experience.', es: 'Controla tu experiencia con Arsenal.', fr: 'Contrôlez votre expérience Arsenal.', de: 'Steuere dein Arsenal-Erlebnis.', tr: 'Arsenal deneyiminizi yönetin.', ru: 'Управляйте работой с Arsenal.', hi: 'अपने Arsenal अनुभव को नियंत्रित करें।', zh: '管理您的 Arsenal 使用体验。' },
  'الحساب': { en: 'Account', es: 'Cuenta', fr: 'Compte', de: 'Konto', tr: 'Hesap', ru: 'Учётная запись', hi: 'खाता', zh: '账户' },
  'سجّل دخولك لمزامنة إعداداتك واشتراكك وفيدباكك.': { en: 'Sign in to sync your settings, subscription, and feedback.', es: 'Inicia sesión para sincronizar tu configuración, suscripción y comentarios.', fr: 'Connectez-vous pour synchroniser vos paramètres, votre abonnement et vos retours.', de: 'Melde dich an, um Einstellungen, Abonnement und Feedback zu synchronisieren.', tr: 'Ayarlarınızı, aboneliğinizi ve geri bildiriminizi eşitlemek için giriş yapın.', ru: 'Войдите, чтобы синхронизировать настройки, подписку и обратную связь.', hi: 'अपनी सेटिंग्स, सदस्यता और फ़ीडबैक सिंक करने के लिए साइन इन करें।', zh: '登录以同步您的设置、订阅和反馈。' },
  'الدخول عبر Google': { en: 'Continue with Google', es: 'Continuar con Google', fr: 'Continuer avec Google', de: 'Mit Google fortfahren', tr: 'Google ile devam et', ru: 'Продолжить с Google', hi: 'Google से जारी रखें', zh: '使用 Google 继续' },
  'خروج': { en: 'Sign out', es: 'Cerrar sesión', fr: 'Se déconnecter', de: 'Abmelden', tr: 'Çıkış yap', ru: 'Выйти', hi: 'साइन आउट करें', zh: '退出登录' },
  'المظهر': { en: 'Appearance', es: 'Apariencia', fr: 'Apparence', de: 'Darstellung', tr: 'Görünüm', ru: 'Внешний вид', hi: 'दिखावट', zh: '外观' },
  'وضع العرض': { en: 'Display mode', es: 'Modo de visualización', fr: 'Mode d’affichage', de: 'Anzeigemodus', tr: 'Görüntüleme modu', ru: 'Режим отображения', hi: 'डिस्प्ले मोड', zh: '显示模式' },
  'الوضع الفاتح': { en: 'Light mode', es: 'Modo claro', fr: 'Mode clair', de: 'Heller Modus', tr: 'Açık mod', ru: 'Светлый режим', hi: 'लाइट मोड', zh: '浅色模式' },
  'الوضع الداكن': { en: 'Dark mode', es: 'Modo oscuro', fr: 'Mode sombre', de: 'Dunkler Modus', tr: 'Koyu mod', ru: 'Тёмный режим', hi: 'डार्क मोड', zh: '深色模式' },
  'صوت التنقل': { en: 'Navigation sound', es: 'Sonido de navegación', fr: 'Son de navigation', de: 'Navigationsklang', tr: 'Gezinme sesi', ru: 'Звук навигации', hi: 'नेविगेशन ध्वनि', zh: '导航提示音' },
  'مفعّل': { en: 'On', es: 'Activado', fr: 'Activé', de: 'Aktiviert', tr: 'Açık', ru: 'Включено', hi: 'चालू', zh: '已开启' },
  'مكتوم': { en: 'Muted', es: 'Silenciado', fr: 'Muet', de: 'Stumm', tr: 'Sessiz', ru: 'Без звука', hi: 'म्यूट', zh: '静音' },
  'دعم المشروع': { en: 'Support the project', es: 'Apoyar el proyecto', fr: 'Soutenir le projet', de: 'Projekt unterstützen', tr: 'Projeyi destekleyin', ru: 'Поддержать проект', hi: 'प्रोजेक्ट को सपोर्ट करें', zh: '支持项目' },
  'عضوية VIP': { en: 'VIP membership', es: 'Membresía VIP', fr: 'Abonnement VIP', de: 'VIP-Mitgliedschaft', tr: 'VIP üyeliği', ru: 'VIP-подписка', hi: 'VIP सदस्यता', zh: 'VIP 会员资格' },
  'ادعم المشروع واحصل على مزايا وخيارات إضافية.': { en: 'Support the project and unlock additional features and options.', es: 'Apoya el proyecto y obtén funciones y opciones adicionales.', fr: 'Soutenez le projet et accédez à des fonctionnalités et options supplémentaires.', de: 'Unterstütze das Projekt und erhalte zusätzliche Funktionen und Optionen.', tr: 'Projeyi destekleyin ve ek özellikler ile seçeneklere erişin.', ru: 'Поддержите проект и получите дополнительные возможности и настройки.', hi: 'प्रोजेक्ट को सपोर्ट करें और अतिरिक्त सुविधाएँ व विकल्प पाएँ।', zh: '支持项目并解锁更多功能与选项。' },
  'الاستخدام بدون إنترنت': { en: 'Offline use', es: 'Uso sin conexión', fr: 'Utilisation hors ligne', de: 'Offline-Nutzung', tr: 'Çevrimdışı kullanım', ru: 'Работа без интернета', hi: 'ऑफ़लाइन उपयोग', zh: '离线使用' },
  'تحميل الصفحات محلياً': { en: 'Save pages locally', es: 'Guardar páginas localmente', fr: 'Enregistrer les pages localement', de: 'Seiten lokal speichern', tr: 'Sayfaları yerel olarak kaydet', ru: 'Сохранить страницы локально', hi: 'पेज स्थानीय रूप से सहेजें', zh: '在本地保存页面' },
  'احفظ صفحة المنصة وروابط الأدوات لفتحها من ذاكرة المتصفح.': { en: 'Save the platform page and tool links for access from your browser cache.', es: 'Guarda la página de la plataforma y los enlaces de herramientas para acceder desde la caché del navegador.', fr: 'Enregistrez la page de la plateforme et les liens des outils pour y accéder depuis le cache du navigateur.', de: 'Speichere Plattformseite und Tool-Links für den Zugriff aus dem Browser-Cache.', tr: 'Platform sayfasını ve araç bağlantılarını tarayıcı önbelleğinden erişmek üzere kaydedin.', ru: 'Сохраните страницу платформы и ссылки на инструменты для доступа из кэша браузера.', hi: 'ब्राउज़र कैश से खोलने के लिए प्लेटफ़ॉर्म पेज और टूल लिंक सहेजें।', zh: '保存平台页面和工具链接，以便从浏览器缓存访问。' },
  'جاري التحضير…': { en: 'Preparing…', es: 'Preparando…', fr: 'Préparation…', de: 'Wird vorbereitet…', tr: 'Hazırlanıyor…', ru: 'Подготовка…', hi: 'तैयार किया जा रहा है…', zh: '正在准备…' },
  'تحميل للاستخدام Offline': { en: 'Save for offline use', es: 'Guardar para usar sin conexión', fr: 'Enregistrer pour une utilisation hors ligne', de: 'Für Offline-Nutzung speichern', tr: 'Çevrimdışı kullanım için kaydet', ru: 'Сохранить для работы без интернета', hi: 'ऑफ़लाइन उपयोग के लिए सहेजें', zh: '保存以供离线使用' },
  'قانوني': { en: 'Legal', es: 'Legal', fr: 'Mentions légales', de: 'Rechtliches', tr: 'Yasal', ru: 'Правовая информация', hi: 'कानूनी', zh: '法律信息' },
  'السياسة والخصوصية': { en: 'Privacy policy', es: 'Política de privacidad', fr: 'Politique de confidentialité', de: 'Datenschutzerklärung', tr: 'Gizlilik politikası', ru: 'Политика конфиденциальности', hi: 'गोपनीयता नीति', zh: '隐私政策' },
  'كيف نتعامل مع بياناتك وملفاتك.': { en: 'How we handle your data and files.', es: 'Cómo tratamos tus datos y archivos.', fr: 'Comment nous traitons vos données et fichiers.', de: 'Wie wir mit deinen Daten und Dateien umgehen.', tr: 'Verilerinizi ve dosyalarınızı nasıl işlediğimiz.', ru: 'Как мы работаем с вашими данными и файлами.', hi: 'हम आपके डेटा और फ़ाइलों को कैसे संभालते हैं।', zh: '我们如何处理您的数据和文件。' },
  'حقوقك والتزاماتك عند استخدام المنصة.': { en: 'Your rights and responsibilities when using the platform.', es: 'Tus derechos y responsabilidades al usar la plataforma.', fr: 'Vos droits et responsabilités lors de l’utilisation de la plateforme.', de: 'Deine Rechte und Pflichten bei der Nutzung der Plattform.', tr: 'Platformu kullanırken haklarınız ve sorumluluklarınız.', ru: 'Ваши права и обязанности при использовании платформы.', hi: 'प्लेटफ़ॉर्म का उपयोग करते समय आपके अधिकार और ज़िम्मेदारियाँ।', zh: '您使用平台时享有的权利和应承担的责任。' },
  'رأيك يهمنا': { en: 'Your feedback matters', es: 'Tu opinión nos importa', fr: 'Votre avis compte', de: 'Dein Feedback zählt', tr: 'Görüşünüz önemli', ru: 'Ваше мнение важно', hi: 'आपकी राय मायने रखती है', zh: '您的意见很重要' },
  'أرسل رأيك': { en: 'Send feedback', es: 'Enviar comentarios', fr: 'Envoyer un avis', de: 'Feedback senden', tr: 'Geri bildirim gönder', ru: 'Отправить отзыв', hi: 'फ़ीडबैक भेजें', zh: '发送反馈' },
  'سجّل دخولك عبر Google لتتمكن من إرسال الفيدباك.': { en: 'Sign in with Google to send feedback.', es: 'Inicia sesión con Google para enviar comentarios.', fr: 'Connectez-vous avec Google pour envoyer un avis.', de: 'Melde dich mit Google an, um Feedback zu senden.', tr: 'Geri bildirim göndermek için Google ile giriş yapın.', ru: 'Войдите через Google, чтобы отправить отзыв.', hi: 'फ़ीडबैक भेजने के लिए Google से साइन इन करें।', zh: '请使用 Google 登录以发送反馈。' },
  'الترسانة · الإصدار المستقل متعدد الصفحات': { en: 'Arsenal · Independent multi-page edition', es: 'Arsenal · Edición independiente de varias páginas', fr: 'Arsenal · Édition indépendante multipage', de: 'Arsenal · Unabhängige Mehrseiten-Ausgabe', tr: 'Arsenal · Bağımsız çok sayfalı sürüm', ru: 'Arsenal · Независимая многостраничная версия', hi: 'Arsenal · स्वतंत्र बहु-पृष्ठ संस्करण', zh: 'Arsenal · 独立多页面版本' }
};
