type TextComparisonTranslationRow = Record<string, string>;

/** النصوص عالية الظهور في مقارنة النصوص؛ يبقى محتوى المستخدم كما أدخله. */
export const reviewedTextComparisonText: Record<string, TextComparisonTranslationRow> = {
  'مقارنة النصوص والكود': { en: 'Text and Code Comparison', es: 'Comparación de texto y código', fr: 'Comparaison de texte et de code', de: 'Text- und Codevergleich', tr: 'Metin ve Kod Karşılaştırma', ru: 'Сравнение текста и кода', hi: 'टेक्स्ट और कोड तुलना', zh: '文本和代码对比' },
  'اكشف الفروقات كلمةً بكلمة — تعمل الأداة محلياً بالكامل.': { en: 'Find differences word by word — entirely in your browser.', es: 'Encuentra diferencias palabra por palabra, directamente en tu navegador.', fr: 'Repérez les différences mot à mot, entièrement dans votre navigateur.', de: 'Unterschiede Wort für Wort finden — vollständig im Browser.', tr: 'Farkları kelime kelime bulun — tamamen tarayıcınızda.', ru: 'Находите различия слово за словом — полностью в браузере.', hi: 'शब्द-दर-शब्द अंतर खोजें — पूरी तरह आपके ब्राउज़र में।', zh: '逐词查找差异，全程在浏览器中完成。' },
  'وضع المقارنة': { en: 'Comparison mode', es: 'Modo de comparación', fr: 'Mode de comparaison', de: 'Vergleichsmodus', tr: 'Karşılaştırma modu', ru: 'Режим сравнения', hi: 'तुलना मोड', zh: '对比模式' },
  'نصوص': { en: 'Text', es: 'Texto', fr: 'Texte', de: 'Text', tr: 'Metin', ru: 'Текст', hi: 'टेक्स्ट', zh: '文本' },
  'كلمة + حرف': { en: 'Word + character', es: 'Palabra + carácter', fr: 'Mot + caractère', de: 'Wort + Zeichen', tr: 'Kelime + karakter', ru: 'Слово + символ', hi: 'शब्द + अक्षर', zh: '词 + 字符' },
  'كود برمجي': { en: 'Code', es: 'Código', fr: 'Code', de: 'Code', tr: 'Kod', ru: 'Код', hi: 'कोड', zh: '代码' },
  'النص الأصلي': { en: 'Original text', es: 'Texto original', fr: 'Texte d’origine', de: 'Originaltext', tr: 'Özgün metin', ru: 'Исходный текст', hi: 'मूल टेक्स्ट', zh: '原始文本' },
  'المرجع': { en: 'Reference', es: 'Referencia', fr: 'Référence', de: 'Referenz', tr: 'Referans', ru: 'Исходный вариант', hi: 'संदर्भ', zh: '参照文本' },
  'أدخل النص الأساسي القديم هنا…': { en: 'Enter the original text here…', es: 'Introduce aquí el texto original…', fr: 'Saisissez ici le texte d’origine…', de: 'Originaltext hier eingeben…', tr: 'Özgün metni buraya girin…', ru: 'Введите исходный текст здесь…', hi: 'मूल टेक्स्ट यहाँ दर्ज करें…', zh: '在此输入原始文本…' },
  'النص الجديد': { en: 'New text', es: 'Texto nuevo', fr: 'Nouveau texte', de: 'Neuer Text', tr: 'Yeni metin', ru: 'Новый текст', hi: 'नया टेक्स्ट', zh: '新文本' },
  'بعد التعديل': { en: 'Edited version', es: 'Versión editada', fr: 'Version modifiée', de: 'Bearbeitete Version', tr: 'Düzenlenmiş sürüm', ru: 'Изменённая версия', hi: 'संपादित संस्करण', zh: '修改后版本' },
  'أدخل النص الجديد بعد التعديل…': { en: 'Enter the edited text here…', es: 'Introduce aquí el texto editado…', fr: 'Saisissez ici le texte modifié…', de: 'Bearbeiteten Text hier eingeben…', tr: 'Düzenlenmiş metni buraya girin…', ru: 'Введите изменённый текст здесь…', hi: 'संपादित टेक्स्ट यहाँ दर्ज करें…', zh: '在此输入修改后的文本…' },
  '{count} سطر': { en: '{count} line(s)', es: '{count} línea(s)', fr: '{count} ligne(s)', de: '{count} Zeile(n)', tr: '{count} satır', ru: '{count} строк', hi: '{count} पंक्ति', zh: '{count} 行' },
  'ابدأ المقارنة وإظهار الفروقات': { en: 'Compare and show differences', es: 'Comparar y mostrar diferencias', fr: 'Comparer et afficher les différences', de: 'Vergleichen und Unterschiede anzeigen', tr: 'Karşılaştır ve farkları göster', ru: 'Сравнить и показать различия', hi: 'तुलना करें और अंतर दिखाएँ', zh: '比较并显示差异' },
  'محذوف': { en: 'Deleted', es: 'Eliminado', fr: 'Supprimé', de: 'Gelöscht', tr: 'Silinen', ru: 'Удалено', hi: 'हटाया गया', zh: '已删除' },
  'مضاف': { en: 'Added', es: 'Añadido', fr: 'Ajouté', de: 'Hinzugefügt', tr: 'Eklenen', ru: 'Добавлено', hi: 'जोड़ा गया', zh: '已添加' },
  'من دون تغيير': { en: 'Unchanged', es: 'Sin cambios', fr: 'Sans modification', de: 'Unverändert', tr: 'Değişmedi', ru: 'Без изменений', hi: 'बिना बदलाव', zh: '未更改' },
  'أدخل نصين للمقارنة': { en: 'Enter two texts to compare', es: 'Introduce dos textos para comparar', fr: 'Saisissez deux textes à comparer', de: 'Zwei Texte zum Vergleichen eingeben', tr: 'Karşılaştırmak için iki metin girin', ru: 'Введите два текста для сравнения', hi: 'तुलना के लिए दो टेक्स्ट दर्ज करें', zh: '输入两个文本进行比较' },
  'نسخ نتيجة المقارنة': { en: 'Copy comparison result', es: 'Copiar resultado de la comparación', fr: 'Copier le résultat de la comparaison', de: 'Vergleichsergebnis kopieren', tr: 'Karşılaştırma sonucunu kopyala', ru: 'Копировать результат сравнения', hi: 'तुलना परिणाम कॉपी करें', zh: '复制对比结果' },
  'أدخل نصاً واحداً على الأقل لبدء المقارنة.': { en: 'Enter at least one text to begin comparison.', es: 'Introduce al menos un texto para iniciar la comparación.', fr: 'Saisissez au moins un texte pour lancer la comparaison.', de: 'Geben Sie mindestens einen Text ein, um den Vergleich zu starten.', tr: 'Karşılaştırmayı başlatmak için en az bir metin girin.', ru: 'Введите хотя бы один текст, чтобы начать сравнение.', hi: 'तुलना शुरू करने के लिए कम से कम एक टेक्स्ट दर्ज करें।', zh: '请至少输入一段文本以开始比较。' },
  'النصان متطابقان تماماً': { en: 'The two texts are identical', es: 'Los dos textos son idénticos', fr: 'Les deux textes sont identiques', de: 'Die beiden Texte sind identisch', tr: 'İki metin tamamen aynı', ru: 'Два текста полностью совпадают', hi: 'दोनों टेक्स्ट बिल्कुल समान हैं', zh: '两段文本完全一致' },
  'لا توجد نتيجة مقارنة لنسخها.': { en: 'There is no comparison result to copy.', es: 'No hay resultado de comparación para copiar.', fr: 'Il n’y a aucun résultat de comparaison à copier.', de: 'Es gibt kein Vergleichsergebnis zum Kopieren.', tr: 'Kopyalanacak karşılaştırma sonucu yok.', ru: 'Нет результата сравнения для копирования.', hi: 'कॉपी करने के लिए कोई तुलना परिणाम नहीं है।', zh: '没有可复制的对比结果。' }
};
