type BackgroundRemoverTranslationRow = Record<string, string>;

/** نصوص مزيل الخلفية المراجَعة، بما فيها رسائل Worker التي تُترجم عند العرض. */
export const reviewedBackgroundRemoverText: Record<string, BackgroundRemoverTranslationRow> = {
  'محرر الخلفية الشفاف': { en: 'Transparent Background Editor', es: 'Editor de fondo transparente', fr: 'Éditeur d’arrière-plan transparent', de: 'Editor für transparente Hintergründe', tr: 'Şeffaf Arka Plan Düzenleyici', ru: 'Редактор прозрачного фона', hi: 'पारदर्शी बैकग्राउंड एडिटर', zh: '透明背景编辑器' },
  'أزل الخلفية تلقائياً بالذكاء الاصطناعي أو صحّح الحواف محلياً بدقة.': { en: 'Remove the background automatically with AI or refine edges precisely, locally.', es: 'Elimina el fondo automáticamente con IA o ajusta los bordes con precisión de forma local.', fr: 'Supprimez automatiquement l’arrière-plan avec l’IA ou ajustez les bords avec précision, localement.', de: 'Hintergrund automatisch mit KI entfernen oder Kanten lokal präzise nachbearbeiten.', tr: 'Arka planı yapay zekâ ile otomatik kaldırın veya kenarları yerel olarak hassas biçimde düzeltin.', ru: 'Автоматически удаляйте фон с помощью ИИ или точно корректируйте края локально.', hi: 'AI से बैकग्राउंड अपने-आप हटाएँ या किनारों को स्थानीय रूप से सटीकता से ठीक करें।', zh: '使用 AI 自动移除背景，或在本地精细修正边缘。' },
  'الصورة': { en: 'Image', es: 'Imagen', fr: 'Image', de: 'Bild', tr: 'Görsel', ru: 'Изображение', hi: 'तस्वीर', zh: '图片' },
  'اضغط هنا لرفع الصورة': { en: 'Click here to upload an image', es: 'Haz clic aquí para subir una imagen', fr: 'Cliquez ici pour importer une image', de: 'Hier klicken, um ein Bild hochzuladen', tr: 'Bir görsel yüklemek için buraya tıklayın', ru: 'Нажмите здесь, чтобы загрузить изображение', hi: 'तस्वीर अपलोड करने के लिए यहाँ क्लिक करें', zh: '点击此处上传图片' },
  'الممحاة': { en: 'Eraser', es: 'Borrador', fr: 'Gomme', de: 'Radierer', tr: 'Silgi', ru: 'Ластик', hi: 'इरेज़र', zh: '橡皮擦' },
  'الاسترجاع': { en: 'Restore', es: 'Restaurar', fr: 'Restaurer', de: 'Wiederherstellen', tr: 'Geri yükle', ru: 'Восстановить', hi: 'बहाल करें', zh: '恢复' },
  'تراجع': { en: 'Undo', es: 'Deshacer', fr: 'Annuler', de: 'Rückgängig', tr: 'Geri al', ru: 'Отменить', hi: 'पूर्ववत करें', zh: '撤销' },
  'إعادة': { en: 'Redo', es: 'Rehacer', fr: 'Rétablir', de: 'Wiederholen', tr: 'Yinele', ru: 'Повторить', hi: 'फिर करें', zh: '重做' },
  'إزالة AI': { en: 'AI removal', es: 'Eliminar con IA', fr: 'Suppression par IA', de: 'KI-Entfernung', tr: 'Yapay zekâ ile kaldır', ru: 'Удалить с ИИ', hi: 'AI से हटाएँ', zh: 'AI 移除' },
  'جاري التحضير…': { en: 'Preparing…', es: 'Preparando…', fr: 'Préparation…', de: 'Vorbereitung…', tr: 'Hazırlanıyor…', ru: 'Подготовка…', hi: 'तैयारी हो रही है…', zh: '正在准备…' },
  'حجم الأداة': { en: 'Tool size', es: 'Tamaño de herramienta', fr: 'Taille de l’outil', de: 'Werkzeuggröße', tr: 'Araç boyutu', ru: 'Размер инструмента', hi: 'टूल आकार', zh: '工具大小' },
  'تنزيل الصورة (PNG شفاف)': { en: 'Download image (transparent PNG)', es: 'Descargar imagen (PNG transparente)', fr: 'Télécharger l’image (PNG transparent)', de: 'Bild herunterladen (transparentes PNG)', tr: 'Görseli indir (şeffaf PNG)', ru: 'Скачать изображение (прозрачный PNG)', hi: 'तस्वीर डाउनलोड करें (पारदर्शी PNG)', zh: '下载图片（透明 PNG）' },
  'جاري فتح الصورة…': { en: 'Opening image…', es: 'Abriendo imagen…', fr: 'Ouverture de l’image…', de: 'Bild wird geöffnet…', tr: 'Görsel açılıyor…', ru: 'Открытие изображения…', hi: 'तस्वीर खोली जा रही है…', zh: '正在打开图片…' },
  'الصورة جاهزة. يمكنك البدء بالممحاة أو الإزالة الذكية.': { en: 'Your image is ready. Start with the eraser or AI removal.', es: 'Tu imagen está lista. Empieza con el borrador o la eliminación con IA.', fr: 'Votre image est prête. Utilisez la gomme ou la suppression par IA.', de: 'Ihr Bild ist bereit. Starten Sie mit dem Radierer oder der KI-Entfernung.', tr: 'Görseliniz hazır. Silgiyle veya yapay zekâ ile kaldırmayla başlayın.', ru: 'Изображение готово. Начните с ластика или удаления с ИИ.', hi: 'तस्वीर तैयार है। इरेज़र या AI रिमूवल से शुरू करें।', zh: '图片已就绪。可使用橡皮擦或 AI 移除功能。' },
  'تعذر فتح الصورة': { en: 'Could not open image', es: 'No se pudo abrir la imagen', fr: 'Impossible d’ouvrir l’image', de: 'Bild konnte nicht geöffnet werden', tr: 'Görsel açılamadı', ru: 'Не удалось открыть изображение', hi: 'तस्वीर नहीं खोली जा सकी', zh: '无法打开图片' },
  'تعذر تحميل الصورة: {reason}': { en: 'Could not load image: {reason}', es: 'No se pudo cargar la imagen: {reason}', fr: 'Impossible de charger l’image : {reason}', de: 'Bild konnte nicht geladen werden: {reason}', tr: 'Görsel yüklenemedi: {reason}', ru: 'Не удалось загрузить изображение: {reason}', hi: 'तस्वीर लोड नहीं हो सकी: {reason}', zh: '无法加载图片：{reason}' },
  'اختر ملف صورة صالحاً فقط.': { en: 'Choose a valid image file only.', es: 'Elige únicamente un archivo de imagen válido.', fr: 'Choisissez uniquement un fichier image valide.', de: 'Wählen Sie nur eine gültige Bilddatei.', tr: 'Yalnızca geçerli bir görsel dosyası seçin.', ru: 'Выберите корректный файл изображения.', hi: 'केवल मान्य तस्वीर फ़ाइल चुनें।', zh: '请选择有效的图片文件。' },
  'جاري تحضير الذكاء الاصطناعي…': { en: 'Preparing AI…', es: 'Preparando la IA…', fr: 'Préparation de l’IA…', de: 'KI wird vorbereitet…', tr: 'Yapay zekâ hazırlanıyor…', ru: 'Подготовка ИИ…', hi: 'AI तैयार हो रहा है…', zh: '正在准备 AI…' },
  'تُحمّل مكتبات الذكاء الاصطناعي عند الطلب فقط.': { en: 'AI libraries load only when needed.', es: 'Las bibliotecas de IA solo se cargan cuando se necesitan.', fr: 'Les bibliothèques d’IA ne se chargent qu’en cas de besoin.', de: 'KI-Bibliotheken werden nur bei Bedarf geladen.', tr: 'Yapay zekâ kitaplıkları yalnızca gerektiğinde yüklenir.', ru: 'Библиотеки ИИ загружаются только при необходимости.', hi: 'AI लाइब्रेरी केवल ज़रूरत होने पर लोड होती हैं।', zh: 'AI 库仅在需要时加载。' },
  'جاري تحميل محرك الذكاء الاصطناعي…': { en: 'Loading AI engine…', es: 'Cargando el motor de IA…', fr: 'Chargement du moteur d’IA…', de: 'KI-Engine wird geladen…', tr: 'Yapay zekâ motoru yükleniyor…', ru: 'Загрузка движка ИИ…', hi: 'AI इंजन लोड हो रहा है…', zh: '正在加载 AI 引擎…' },
  'جاري تحميل نموذج إزالة الخلفية…': { en: 'Loading background-removal model…', es: 'Cargando el modelo de eliminación de fondo…', fr: 'Chargement du modèle de suppression d’arrière-plan…', de: 'Modell zur Hintergrundentfernung wird geladen…', tr: 'Arka plan kaldırma modeli yükleniyor…', ru: 'Загрузка модели удаления фона…', hi: 'बैकग्राउंड रिमूवल मॉडल लोड हो रहा है…', zh: '正在加载背景移除模型…' },
  'جاري تحليل الصورة…': { en: 'Analyzing image…', es: 'Analizando imagen…', fr: 'Analyse de l’image…', de: 'Bild wird analysiert…', tr: 'Görsel analiz ediliyor…', ru: 'Анализ изображения…', hi: 'तस्वीर का विश्लेषण हो रहा है…', zh: '正在分析图片…' },
  'جاري تحليل الصورة محلياً…': { en: 'Analyzing image locally…', es: 'Analizando la imagen de forma local…', fr: 'Analyse locale de l’image…', de: 'Bild wird lokal analysiert…', tr: 'Görsel yerel olarak analiz ediliyor…', ru: 'Локальный анализ изображения…', hi: 'तस्वीर का स्थानीय रूप से विश्लेषण हो रहा है…', zh: '正在本地分析图片…' },
  'اكتملت إزالة الخلفية بنجاح': { en: 'Background removal completed successfully', es: 'La eliminación de fondo se completó correctamente', fr: 'La suppression de l’arrière-plan est terminée avec succès', de: 'Hintergrundentfernung erfolgreich abgeschlossen', tr: 'Arka plan kaldırma başarıyla tamamlandı', ru: 'Удаление фона успешно завершено', hi: 'बैकग्राउंड रिमूवल सफलतापूर्वक पूरा हुआ', zh: '背景移除成功完成' },
  'اكتملت إزالة الخلفية محلياً. صحح الحواف بالفرشاة إذا احتجت.': { en: 'Background removal completed locally. Refine edges with the brush if needed.', es: 'La eliminación de fondo se completó localmente. Ajusta los bordes con el pincel si hace falta.', fr: 'La suppression de l’arrière-plan est terminée localement. Ajustez les bords au pinceau si nécessaire.', de: 'Die Hintergrundentfernung wurde lokal abgeschlossen. Bei Bedarf Kanten mit dem Pinsel nachbearbeiten.', tr: 'Arka plan kaldırma yerel olarak tamamlandı. Gerekirse kenarları fırçayla düzeltin.', ru: 'Удаление фона завершено локально. При необходимости уточните края кистью.', hi: 'बैकग्राउंड रिमूवल स्थानीय रूप से पूरा हुआ। ज़रूरत हो तो ब्रश से किनारों को ठीक करें।', zh: '背景移除已在本地完成。如有需要，可用画笔修正边缘。' },
  'تعذر إكمال الإزالة': { en: 'Could not complete removal', es: 'No se pudo completar la eliminación', fr: 'Impossible de terminer la suppression', de: 'Entfernung konnte nicht abgeschlossen werden', tr: 'Kaldırma tamamlanamadı', ru: 'Не удалось завершить удаление', hi: 'रिमूवल पूरा नहीं हो सका', zh: '无法完成移除' },
  'فشلت إزالة الخلفية: {reason}': { en: 'Background removal failed: {reason}', es: 'Falló la eliminación de fondo: {reason}', fr: 'Échec de la suppression de l’arrière-plan : {reason}', de: 'Hintergrundentfernung fehlgeschlagen: {reason}', tr: 'Arka plan kaldırma başarısız: {reason}', ru: 'Не удалось удалить фон: {reason}', hi: 'बैकग्राउंड रिमूवल विफल: {reason}', zh: '背景移除失败：{reason}' },
  'تعذر تشغيل معالجة AI: {reason}': { en: 'Could not start AI processing: {reason}', es: 'No se pudo iniciar el procesamiento de IA: {reason}', fr: 'Impossible de démarrer le traitement par IA : {reason}', de: 'KI-Verarbeitung konnte nicht gestartet werden: {reason}', tr: 'Yapay zekâ işleme başlatılamadı: {reason}', ru: 'Не удалось запустить обработку ИИ: {reason}', hi: 'AI प्रोसेसिंग शुरू नहीं हो सकी: {reason}', zh: '无法启动 AI 处理：{reason}' },
  'خطأ غير متوقع': { en: 'Unexpected error', es: 'Error inesperado', fr: 'Erreur inattendue', de: 'Unerwarteter Fehler', tr: 'Beklenmeyen hata', ru: 'Непредвиденная ошибка', hi: 'अनपेक्षित त्रुटि', zh: '意外错误' }
};
