type LocalShareTranslationRow = Record<string, string>;

/** نصوص Arsenal Share Pro المراجَعة؛ تبقى أسماء البروتوكولات WebRTC وDTLS وE2E وQR كما هي. */
export const reviewedLocalShareText: Record<string, LocalShareTranslationRow> = {
  'نقل مباشر بين جهازين عبر WebRTC، مع تشفير DTLS تلقائي ومصافحة QR أو رمز يدوي.': { en: 'Direct device-to-device transfer over WebRTC, with automatic DTLS encryption and QR or manual-code pairing.', es: 'Transferencia directa entre dispositivos con WebRTC, cifrado DTLS automático y vinculación por QR o código manual.', fr: 'Transfert direct entre appareils via WebRTC, avec chiffrement DTLS automatique et appairage par QR ou code manuel.', de: 'Direkte Geräteübertragung über WebRTC mit automatischer DTLS-Verschlüsselung und Kopplung per QR oder manuellem Code.', tr: 'Otomatik DTLS şifreleme ve QR ya da manuel kod eşleştirmesiyle WebRTC üzerinden doğrudan cihazlar arası aktarım.', ru: 'Прямая передача между устройствами через WebRTC с автоматическим шифрованием DTLS и сопряжением по QR или вручную.', hi: 'WebRTC के ज़रिए सीधे डिवाइस-टू-डिवाइस ट्रांसफ़र, ऑटोमैटिक DTLS एन्क्रिप्शन और QR या मैनुअल-कोड पेयरिंग के साथ।', zh: '通过 WebRTC 在设备间直接传输，支持自动 DTLS 加密以及二维码或手动代码配对。' },
  'جاهز لإنشاء جلسة آمنة': { en: 'Ready to create a secure session', es: 'Listo para crear una sesión segura', fr: 'Prêt à créer une session sécurisée', de: 'Bereit, eine sichere Sitzung zu erstellen', tr: 'Güvenli oturum oluşturmaya hazır', ru: 'Готов к созданию защищённого сеанса', hi: 'सुरक्षित सत्र बनाने के लिए तैयार', zh: '已准备好创建安全会话' },
  'إرسال — إنشاء جلسة': { en: 'Send — create a session', es: 'Enviar — crear una sesión', fr: 'Envoyer — créer une session', de: 'Senden — Sitzung erstellen', tr: 'Gönder — oturum oluştur', ru: 'Отправить — создать сеанс', hi: 'भेजें — सत्र बनाएँ', zh: '发送 — 创建会话' },
  'استقبال — مسح QR': { en: 'Receive — scan QR', es: 'Recibir — escanear QR', fr: 'Recevoir — scanner le QR', de: 'Empfangen — QR scannen', tr: 'Al — QR tara', ru: 'Получить — сканировать QR', hi: 'प्राप्त करें — QR स्कैन करें', zh: '接收 — 扫描二维码' },
  'توليد رمز QR لجلسة الإرسال': { en: 'Create QR code for sending session', es: 'Crear código QR para la sesión de envío', fr: 'Créer un code QR pour la session d’envoi', de: 'QR-Code für die Übertragungssitzung erstellen', tr: 'Gönderim oturumu için QR kodu oluştur', ru: 'Создать QR-код для сеанса отправки', hi: 'भेजने के सत्र के लिए QR कोड बनाएँ', zh: '为发送会话创建二维码' },
  '1. اطلب من المستلم مسح هذا الرمز أو نسخ الرمز اليدوي.': { en: '1. Ask the recipient to scan this code or copy the manual code.', es: '1. Pide al destinatario que escanee este código o copie el código manual.', fr: '1. Demandez au destinataire de scanner ce code ou de copier le code manuel.', de: '1. Bitten Sie den Empfänger, diesen Code zu scannen oder den manuellen Code zu kopieren.', tr: '1. Alıcıdan bu kodu taramasını veya manuel kodu kopyalamasını isteyin.', ru: '1. Попросите получателя отсканировать этот код или скопировать код вручную.', hi: '1. प्राप्तकर्ता से यह कोड स्कैन करने या मैनुअल कोड कॉपी करने को कहें।', zh: '1. 请接收方扫描此二维码或复制手动代码。' },
  '2. ألصق رمز ردّ المستلم هنا لإتمام الاتصال.': { en: '2. Paste the recipient’s response code here to complete the connection.', es: '2. Pega aquí el código de respuesta del destinatario para completar la conexión.', fr: '2. Collez ici le code de réponse du destinataire pour finaliser la connexion.', de: '2. Antwortcode des Empfängers hier einfügen, um die Verbindung herzustellen.', tr: '2. Bağlantıyı tamamlamak için alıcının yanıt kodunu buraya yapıştırın.', ru: '2. Вставьте код ответа получателя, чтобы завершить подключение.', hi: '2. कनेक्शन पूरा करने के लिए प्राप्तकर्ता का उत्तर कोड यहाँ पेस्ट करें।', zh: '2. 在此粘贴接收方的回应代码以完成连接。' },
  '1. امسح رمز QR الخاص بالمرسل أو ألصق رمز العرض يدوياً.': { en: '1. Scan the sender’s QR code or paste the offer code manually.', es: '1. Escanea el código QR del remitente o pega el código de oferta manualmente.', fr: '1. Scannez le code QR de l’expéditeur ou collez le code d’offre manuellement.', de: '1. QR-Code des Senders scannen oder Angebotscode manuell einfügen.', tr: '1. Gönderenin QR kodunu tarayın veya teklif kodunu elle yapıştırın.', ru: '1. Отсканируйте QR-код отправителя или вставьте код предложения вручную.', hi: '1. प्रेषक का QR कोड स्कैन करें या ऑफ़र कोड मैन्युअल रूप से पेस्ट करें।', zh: '1. 扫描发送方的二维码，或手动粘贴邀请代码。' },
  'فتح الكاميرا': { en: 'Open camera', es: 'Abrir cámara', fr: 'Ouvrir la caméra', de: 'Kamera öffnen', tr: 'Kamerayı aç', ru: 'Открыть камеру', hi: 'कैमरा खोलें', zh: '打开相机' },
  'ألصق رمز المرسل هنا…': { en: 'Paste the sender’s code here…', es: 'Pega aquí el código del remitente…', fr: 'Collez ici le code de l’expéditeur…', de: 'Code des Senders hier einfügen…', tr: 'Gönderenin kodunu buraya yapıştırın…', ru: 'Вставьте код отправителя здесь…', hi: 'प्रेषक का कोड यहाँ पेस्ट करें…', zh: '在此粘贴发送方代码…' },
  'الملفات': { en: 'Files', es: 'Archivos', fr: 'Fichiers', de: 'Dateien', tr: 'Dosyalar', ru: 'Файлы', hi: 'फ़ाइलें', zh: '文件' },
  'اضغط أو اسحب الملفات أو المجلدات هنا للإرسال': { en: 'Click or drop files and folders here to send', es: 'Haz clic o arrastra aquí archivos y carpetas para enviar', fr: 'Cliquez ou déposez ici des fichiers et dossiers à envoyer', de: 'Dateien und Ordner zum Senden hier ablegen oder klicken', tr: 'Göndermek için dosya ve klasörleri buraya tıklayın veya bırakın', ru: 'Нажмите или перетащите сюда файлы и папки для отправки', hi: 'भेजने के लिए यहाँ फ़ाइलें और फ़ोल्डर क्लिक करें या खींचें', zh: '点击或将文件和文件夹拖到此处发送' },
  'يُضغط اختيار الملفات المتعددة تلقائياً في ZIP قبل النقل.': { en: 'Multiple selected files are automatically compressed into a ZIP before transfer.', es: 'Los archivos seleccionados se comprimen automáticamente en un ZIP antes de transferirse.', fr: 'Les fichiers sélectionnés sont automatiquement compressés dans un ZIP avant le transfert.', de: 'Mehrere ausgewählte Dateien werden vor der Übertragung automatisch in eine ZIP-Datei komprimiert.', tr: 'Birden çok seçili dosya aktarım öncesinde otomatik olarak ZIP içinde sıkıştırılır.', ru: 'Несколько выбранных файлов автоматически сжимаются в ZIP перед передачей.', hi: 'कई चुनी गई फ़ाइलें ट्रांसफ़र से पहले अपने-आप ZIP में कंप्रेस हो जाती हैं।', zh: '多个选定文件会在传输前自动压缩为 ZIP。' },
  'إرسال الآن': { en: 'Send now', es: 'Enviar ahora', fr: 'Envoyer maintenant', de: 'Jetzt senden', tr: 'Şimdi gönder', ru: 'Отправить сейчас', hi: 'अभी भेजें', zh: '立即发送' },
  'إلغاء النقل': { en: 'Cancel transfer', es: 'Cancelar transferencia', fr: 'Annuler le transfert', de: 'Übertragung abbrechen', tr: 'Aktarımı iptal et', ru: 'Отменить передачу', hi: 'ट्रांसफ़र रद्द करें', zh: '取消传输' },
  'سجل العمليات': { en: 'Activity log', es: 'Registro de actividad', fr: 'Journal d’activité', de: 'Aktivitätsprotokoll', tr: 'İşlem günlüğü', ru: 'Журнал действий', hi: 'गतिविधि लॉग', zh: '活动日志' },
  'بانتظار اتصال الجهاز الآخر…': { en: 'Waiting for the other device to connect…', es: 'Esperando la conexión del otro dispositivo…', fr: 'En attente de la connexion de l’autre appareil…', de: 'Warte auf Verbindung des anderen Geräts…', tr: 'Diğer cihazın bağlanması bekleniyor…', ru: 'Ожидание подключения другого устройства…', hi: 'दूसरे डिवाइस के कनेक्ट होने की प्रतीक्षा है…', zh: '正在等待另一台设备连接…' },
  'إنهاء الاتصال والمغادرة': { en: 'Disconnect and leave', es: 'Desconectar y salir', fr: 'Se déconnecter et quitter', de: 'Verbindung trennen und verlassen', tr: 'Bağlantıyı kes ve ayrıl', ru: 'Отключиться и выйти', hi: 'डिस्कनेक्ट करें और छोड़ें', zh: '断开连接并离开' },
  'رمز العرض': { en: 'Offer code', es: 'Código de oferta', fr: 'Code d’offre', de: 'Angebotscode', tr: 'Teklif kodu', ru: 'Код предложения', hi: 'ऑफ़र कोड', zh: '邀请代码' },
  'نسخ الرمز': { en: 'Copy code', es: 'Copiar código', fr: 'Copier le code', de: 'Code kopieren', tr: 'Kodu kopyala', ru: 'Копировать код', hi: 'कोड कॉपी करें', zh: '复制代码' },
  'ألصق رمز الرد هنا…': { en: 'Paste the response code here…', es: 'Pega aquí el código de respuesta…', fr: 'Collez ici le code de réponse…', de: 'Antwortcode hier einfügen…', tr: 'Yanıt kodunu buraya yapıştırın…', ru: 'Вставьте код ответа здесь…', hi: 'उत्तर कोड यहाँ पेस्ट करें…', zh: '在此粘贴回应代码…' },
  'قراءة رمز المرسل': { en: 'Read sender code', es: 'Leer código del remitente', fr: 'Lire le code de l’expéditeur', de: 'Sendercode lesen', tr: 'Gönderen kodunu oku', ru: 'Прочитать код отправителя', hi: 'प्रेषक कोड पढ़ें', zh: '读取发送方代码' },
  'رمز الرد': { en: 'Response code', es: 'Código de respuesta', fr: 'Code de réponse', de: 'Antwortcode', tr: 'Yanıt kodu', ru: 'Код ответа', hi: 'उत्तर कोड', zh: '回应代码' },
  'نسخ رمز الرد': { en: 'Copy response code', es: 'Copiar código de respuesta', fr: 'Copier le code de réponse', de: 'Antwortcode kopieren', tr: 'Yanıt kodunu kopyala', ru: 'Копировать код ответа', hi: 'उत्तर कोड कॉपी करें', zh: '复制回应代码' },
  'تمت القراءة. اطلب من المرسل مسح هذا الرد أو نسخه.': { en: 'Code read. Ask the sender to scan or copy this response.', es: 'Código leído. Pide al remitente que escanee o copie esta respuesta.', fr: 'Code lu. Demandez à l’expéditeur de scanner ou copier cette réponse.', de: 'Code gelesen. Bitten Sie den Sender, diese Antwort zu scannen oder zu kopieren.', tr: 'Kod okundu. Gönderenden bu yanıtı taramasını veya kopyalamasını isteyin.', ru: 'Код прочитан. Попросите отправителя отсканировать или скопировать этот ответ.', hi: 'कोड पढ़ लिया गया। प्रेषक से इस उत्तर को स्कैन या कॉपी करने के लिए कहें।', zh: '代码已读取。请发送方扫描或复制此回应。' }
};
