type QrGeneratorTranslationRow = Record<string, string>;

/** نصوص مولد وقارئ QR المراجَعة؛ تظل قيم QR التي يقرأها المستخدم كما هي. */
export const reviewedQrGeneratorText: Record<string, QrGeneratorTranslationRow> = {
  'رمز QR': { en: 'QR Code', es: 'Código QR', fr: 'Code QR', de: 'QR-Code', tr: 'QR Kodu', ru: 'QR-код', hi: 'QR कोड', zh: '二维码' },
  'أداة احترافية لتوليد وقراءة رموز QR بشكل آمن ومحلي.': { en: 'A professional tool to create and read QR codes securely, locally.', es: 'Una herramienta profesional para crear y leer códigos QR de forma segura y local.', fr: 'Un outil professionnel pour créer et lire des codes QR de manière sécurisée et locale.', de: 'Ein professionelles Werkzeug zum sicheren lokalen Erstellen und Lesen von QR-Codes.', tr: 'QR kodlarını güvenli ve yerel olarak oluşturmak ve okumak için profesyonel bir araç.', ru: 'Профессиональный инструмент для безопасного локального создания и чтения QR-кодов.', hi: 'QR कोड को सुरक्षित रूप से स्थानीय तौर पर बनाने और पढ़ने के लिए प्रोफेशनल टूल।', zh: '专业工具，可安全地在本地生成和读取二维码。' },
  'توليد رمز': { en: 'Create code', es: 'Crear código', fr: 'Créer un code', de: 'Code erstellen', tr: 'Kod oluştur', ru: 'Создать код', hi: 'कोड बनाएँ', zh: '生成二维码' },
  'قارئ QR': { en: 'QR reader', es: 'Lector QR', fr: 'Lecteur QR', de: 'QR-Leser', tr: 'QR okuyucu', ru: 'Сканер QR', hi: 'QR रीडर', zh: '二维码读取器' },
  'توليد رمز جديد': { en: 'Create a new code', es: 'Crear un código nuevo', fr: 'Créer un nouveau code', de: 'Neuen Code erstellen', tr: 'Yeni kod oluştur', ru: 'Создать новый код', hi: 'नया कोड बनाएँ', zh: '生成新二维码' },
  'أدخل رابطاً أو نصاً أدناه لتوليد رمز QR.': { en: 'Enter a link or text below to create a QR code.', es: 'Introduce un enlace o texto para crear un código QR.', fr: 'Saisissez un lien ou du texte ci-dessous pour créer un code QR.', de: 'Geben Sie unten einen Link oder Text ein, um einen QR-Code zu erstellen.', tr: 'QR kodu oluşturmak için aşağıya bir bağlantı veya metin girin.', ru: 'Введите ссылку или текст ниже, чтобы создать QR-код.', hi: 'QR कोड बनाने के लिए नीचे लिंक या टेक्स्ट दर्ज करें।', zh: '在下方输入链接或文本以生成二维码。' },
  'https://example.com أو أي نص': { en: 'https://example.com or any text', es: 'https://example.com o cualquier texto', fr: 'https://example.com ou tout texte', de: 'https://example.com oder ein beliebiger Text', tr: 'https://example.com veya herhangi bir metin', ru: 'https://example.com или любой текст', hi: 'https://example.com या कोई भी टेक्स्ट', zh: 'https://example.com 或任何文本' },
  'رمز QR الناتج': { en: 'Generated QR code', es: 'Código QR generado', fr: 'Code QR généré', de: 'Generierter QR-Code', tr: 'Oluşturulan QR kodu', ru: 'Созданный QR-код', hi: 'बनाया गया QR कोड', zh: '已生成的二维码' },
  'توليد الرمز': { en: 'Create code', es: 'Crear código', fr: 'Créer le code', de: 'Code erstellen', tr: 'Kod oluştur', ru: 'Создать код', hi: 'कोड बनाएँ', zh: '生成二维码' },
  'تنزيل PNG': { en: 'Download PNG', es: 'Descargar PNG', fr: 'Télécharger le PNG', de: 'PNG herunterladen', tr: 'PNG indir', ru: 'Скачать PNG', hi: 'PNG डाउनलोड करें', zh: '下载 PNG' },
  'قارئ ومسح الرموز': { en: 'Code reader and scanner', es: 'Lector y escáner de códigos', fr: 'Lecteur et scanner de codes', de: 'Code-Leser und Scanner', tr: 'Kod okuyucu ve tarayıcı', ru: 'Чтение и сканирование кодов', hi: 'कोड रीडर और स्कैनर', zh: '二维码读取和扫描' },
  'ارفع صورة رمز مباشرة أو استخدم المسح عبر الكاميرا.': { en: 'Upload a code image directly or scan it with your camera.', es: 'Sube una imagen de código directamente o escanéala con la cámara.', fr: 'Importez directement une image de code ou scannez-la avec votre caméra.', de: 'Laden Sie ein Codebild hoch oder scannen Sie es mit der Kamera.', tr: 'Doğrudan bir kod görseli yükleyin veya kamerayla tarayın.', ru: 'Загрузите изображение кода или отсканируйте его камерой.', hi: 'कोड की तस्वीर सीधे अपलोड करें या कैमरे से स्कैन करें।', zh: '直接上传二维码图片或使用相机扫描。' },
  'رفع صورة': { en: 'Upload image', es: 'Subir imagen', fr: 'Importer une image', de: 'Bild hochladen', tr: 'Görsel yükle', ru: 'Загрузить изображение', hi: 'तस्वीर अपलोड करें', zh: '上传图片' },
  'كاميرا مباشرة': { en: 'Live camera', es: 'Cámara en directo', fr: 'Caméra en direct', de: 'Live-Kamera', tr: 'Canlı kamera', ru: 'Камера в реальном времени', hi: 'लाइव कैमरा', zh: '实时相机' },
  'اضغط هنا لاختيار صورة من المعرض': { en: 'Click here to choose an image from your gallery', es: 'Haz clic aquí para elegir una imagen de tu galería', fr: 'Cliquez ici pour choisir une image dans votre galerie', de: 'Hier klicken, um ein Bild aus Ihrer Galerie auszuwählen', tr: 'Galerinizden bir görsel seçmek için buraya tıklayın', ru: 'Нажмите здесь, чтобы выбрать изображение из галереи', hi: 'गैलरी से तस्वीर चुनने के लिए यहाँ क्लिक करें', zh: '点击此处从图库选择图片' },
  'خيار آمن وسريع من دون فتح الكاميرا': { en: 'A secure, fast option without opening your camera', es: 'Una opción rápida y segura sin abrir la cámara', fr: 'Une option sûre et rapide sans ouvrir la caméra', de: 'Eine sichere, schnelle Option ohne die Kamera zu öffnen', tr: 'Kamerayı açmadan güvenli ve hızlı bir seçenek', ru: 'Безопасный и быстрый вариант без открытия камеры', hi: 'कैमरा खोले बिना सुरक्षित और तेज़ विकल्प', zh: '无需打开相机的安全快速选项' },
  'مسح رمز آخر': { en: 'Scan another code', es: 'Escanear otro código', fr: 'Scanner un autre code', de: 'Anderen Code scannen', tr: 'Başka kod tara', ru: 'Сканировать другой код', hi: 'दूसरा कोड स्कैन करें', zh: '扫描其他二维码' },
  'بيانات الرمز المستخرجة': { en: 'Extracted code data', es: 'Datos extraídos del código', fr: 'Données extraites du code', de: 'Extrahierte Codedaten', tr: 'Çıkarılan kod verileri', ru: 'Извлечённые данные кода', hi: 'निकाला गया कोड डेटा', zh: '提取的二维码数据' },
  'لم يتم المسح بعد…': { en: 'Nothing scanned yet…', es: 'Aún no se ha escaneado nada…', fr: 'Aucun code n’a encore été scanné…', de: 'Noch nichts gescannt…', tr: 'Henüz tarama yapılmadı…', ru: 'Сканирование ещё не выполнено…', hi: 'अभी कुछ स्कैन नहीं हुआ…', zh: '尚未扫描任何内容…' },
  'نسخ النص': { en: 'Copy text', es: 'Copiar texto', fr: 'Copier le texte', de: 'Text kopieren', tr: 'Metni kopyala', ru: 'Копировать текст', hi: 'टेक्स्ट कॉपी करें', zh: '复制文本' },
  'فتح الرابط': { en: 'Open link', es: 'Abrir enlace', fr: 'Ouvrir le lien', de: 'Link öffnen', tr: 'Bağlantıyı aç', ru: 'Открыть ссылку', hi: 'लिंक खोलें', zh: '打开链接' },
  'أدخل نصاً أو رابطاً أولاً.': { en: 'Enter text or a link first.', es: 'Introduce primero un texto o enlace.', fr: 'Saisissez d’abord du texte ou un lien.', de: 'Geben Sie zuerst Text oder einen Link ein.', tr: 'Önce metin veya bağlantı girin.', ru: 'Сначала введите текст или ссылку.', hi: 'पहले टेक्स्ट या लिंक दर्ज करें।', zh: '请先输入文本或链接。' },
  'تعذر فتح الكاميرا. يمكنك رفع صورة رمز QR بدلاً من ذلك.': { en: 'Could not open the camera. Upload a QR code image instead.', es: 'No se pudo abrir la cámara. Sube una imagen de código QR en su lugar.', fr: 'Impossible d’ouvrir la caméra. Importez plutôt une image de code QR.', de: 'Kamera konnte nicht geöffnet werden. Laden Sie stattdessen ein QR-Code-Bild hoch.', tr: 'Kamera açılamadı. Bunun yerine bir QR kodu görseli yükleyin.', ru: 'Не удалось открыть камеру. Вместо этого загрузите изображение QR-кода.', hi: 'कैमरा नहीं खुल सका। इसके बजाय QR कोड की तस्वीर अपलोड करें।', zh: '无法打开相机。请改为上传二维码图片。' },
  'لم يتم العثور على رمز QR صالح في الصورة.': { en: 'No valid QR code was found in the image.', es: 'No se encontró un código QR válido en la imagen.', fr: 'Aucun code QR valide n’a été trouvé dans l’image.', de: 'Kein gültiger QR-Code im Bild gefunden.', tr: 'Görselde geçerli bir QR kodu bulunamadı.', ru: 'На изображении не найден действительный QR-код.', hi: 'तस्वीर में कोई मान्य QR कोड नहीं मिला।', zh: '图片中未找到有效的二维码。' },
  'تعذر إنشاء رمز QR.': { en: 'Could not create QR code.', es: 'No se pudo crear el código QR.', fr: 'Impossible de créer le code QR.', de: 'QR-Code konnte nicht erstellt werden.', tr: 'QR kodu oluşturulamadı.', ru: 'Не удалось создать QR-код.', hi: 'QR कोड नहीं बनाया जा सका।', zh: '无法生成二维码。' },
  'لا توجد بيانات رمز لنسخها.': { en: 'There is no code data to copy.', es: 'No hay datos de código para copiar.', fr: 'Il n’y a aucune donnée de code à copier.', de: 'Es gibt keine Codedaten zum Kopieren.', tr: 'Kopyalanacak kod verisi yok.', ru: 'Нет данных кода для копирования.', hi: 'कॉपी करने के लिए कोई कोड डेटा नहीं है।', zh: '没有可复制的二维码数据。' }
};
