type GuideTranslationRow = Record<string, string>;

/** نصوص دليل الأدوات التي تظهر بكثافة وتحتاج إلى صياغة بشرية متسقة. */
export const reviewedGuideText: Record<string, GuideTranslationRow> = {
  'دليل الأدوات المستقلة': { en: 'Independent tools guide', es: 'Guía de herramientas independientes', fr: 'Guide des outils indépendants', de: 'Leitfaden für unabhängige Tools', tr: 'Bağımsız araçlar rehberi', ru: 'Гид по автономным инструментам', hi: 'स्वतंत्र टूल गाइड', zh: '独立工具指南' },
  'كل أداة في صفحة مستقلة، وكل مهمة بخطوات واضحة.': { en: 'Each tool has its own page, and every task has clear steps.', es: 'Cada herramienta tiene su propia página y cada tarea cuenta con pasos claros.', fr: 'Chaque outil possède sa propre page et chaque tâche suit des étapes claires.', de: 'Jedes Tool hat eine eigene Seite und jede Aufgabe klare Schritte.', tr: 'Her aracın ayrı bir sayfası ve her görevin açık adımları vardır.', ru: 'У каждого инструмента своя страница, а у каждой задачи — понятные шаги.', hi: 'हर टूल का अपना पेज है और हर कार्य के स्पष्ट चरण हैं।', zh: '每个工具都有独立页面，每项任务都有清晰步骤。' },
  'اختر أداتك مباشرة. تعمل المعالجة داخل المتصفح مع الحفاظ على الخصوصية، وتبقى كل صفحة قابلة للوصول والاختبار دون طبقات تشغيل وسيطة.': { en: 'Choose your tool directly. Processing runs in the browser while preserving privacy, and each page stays accessible and testable without intermediary layers.', es: 'Elige tu herramienta directamente. El procesamiento se realiza en el navegador respetando la privacidad y cada página sigue siendo accesible y comprobable sin capas intermedias.', fr: 'Choisissez directement votre outil. Le traitement s’exécute dans le navigateur tout en préservant la confidentialité, et chaque page reste accessible et testable sans couche intermédiaire.', de: 'Wähle dein Tool direkt. Die Verarbeitung läuft im Browser und wahrt die Privatsphäre; jede Seite bleibt ohne Zwischenschichten zugänglich und testbar.', tr: 'Aracınızı doğrudan seçin. İşleme gizliliği koruyarak tarayıcıda çalışır ve her sayfa aracı katmanlar olmadan erişilebilir ve test edilebilir kalır.', ru: 'Выберите нужный инструмент напрямую. Обработка выполняется в браузере с сохранением конфиденциальности, а каждая страница остаётся доступной и проверяемой без промежуточных слоёв.', hi: 'अपना टूल सीधे चुनें। प्रोसेसिंग गोपनीयता बनाए रखते हुए ब्राउज़र में होती है और हर पेज किसी मध्यस्थ लेयर के बिना सुलभ और परीक्षण योग्य रहता है।', zh: '直接选择所需工具。处理在浏览器中进行，同时保护隐私；每个页面都保持可访问、可测试，无需中间运行层。' },
  'ابدأ من الأداة التي تحتاجها؛': { en: 'Start with the tool you need;', es: 'Empieza con la herramienta que necesitas;', fr: 'Commencez par l’outil dont vous avez besoin ;', de: 'Beginne mit dem Tool, das du brauchst;', tr: 'İhtiyacınız olan araçla başlayın;', ru: 'Начните с нужного вам инструмента;', hi: 'जिस टूल की आपको ज़रूरत है, उससे शुरू करें;', zh: '从您需要的工具开始；' },
  'الملفات لا تغادر جهازك': { en: 'Your files never leave your device', es: 'Tus archivos nunca salen de tu dispositivo', fr: 'Vos fichiers ne quittent jamais votre appareil', de: 'Deine Dateien verlassen dein Gerät nie', tr: 'Dosyalarınız cihazınızdan asla ayrılmaz', ru: 'Ваши файлы никогда не покидают устройство', hi: 'आपकी फ़ाइलें कभी आपके डिवाइस से बाहर नहीं जातीं', zh: '您的文件永不离开设备' },
  'إلا إذا اخترت أنت خلاف ذلك.': { en: 'unless you choose otherwise.', es: 'salvo que elijas lo contrario.', fr: 'sauf si vous en décidez autrement.', de: 'es sei denn, du entscheidest dich anders.', tr: 'siz aksini seçmedikçe.', ru: 'если только вы не выберете иное.', hi: 'जब तक आप स्वयं अन्यथा न चुनें।', zh: '除非您另行选择。' },
  'فيديو': { en: 'Video', es: 'Vídeo', fr: 'Vidéo', de: 'Video', tr: 'Video', ru: 'Видео', hi: 'वीडियो', zh: '视频' },
  'صوت': { en: 'Audio', es: 'Audio', fr: 'Audio', de: 'Audio', tr: 'Ses', ru: 'Аудио', hi: 'ऑडियो', zh: '音频' },
  'صور': { en: 'Images', es: 'Imágenes', fr: 'Images', de: 'Bilder', tr: 'Görseller', ru: 'Изображения', hi: 'इमेज', zh: '图像' },
  'مستندات': { en: 'Documents', es: 'Documentos', fr: 'Documents', de: 'Dokumente', tr: 'Belgeler', ru: 'Документы', hi: 'दस्तावेज़', zh: '文档' },
  'نصوص': { en: 'Text', es: 'Texto', fr: 'Texte', de: 'Text', tr: 'Metin', ru: 'Текст', hi: 'टेक्स्ट', zh: '文本' },
  'متنوعة': { en: 'Utilities', es: 'Utilidades', fr: 'Utilitaires', de: 'Dienstprogramme', tr: 'Yardımcı araçlar', ru: 'Утилиты', hi: 'उपयोगिताएँ', zh: '实用工具' },
  'محلي في المتصفح': { en: 'Runs locally in browser', es: 'Funciona localmente en el navegador', fr: 'Fonctionne localement dans le navigateur', de: 'Läuft lokal im Browser', tr: 'Tarayıcıda yerel çalışır', ru: 'Работает локально в браузере', hi: 'ब्राउज़र में स्थानीय रूप से चलता है', zh: '在浏览器本地运行' },
  'رابط مباشر': { en: 'Direct access', es: 'Acceso directo', fr: 'Accès direct', de: 'Direkter Zugriff', tr: 'Doğrudan erişim', ru: 'Прямой доступ', hi: 'सीधी पहुँच', zh: '直接访问' },
  'استخدام سريع:': { en: 'Quick start:', es: 'Inicio rápido:', fr: 'Démarrage rapide :', de: 'Schnellstart:', tr: 'Hızlı başlangıç:', ru: 'Быстрый старт:', hi: 'त्वरित शुरुआत:', zh: '快速开始：' },
  'فتح الأداة': { en: 'Open tool', es: 'Abrir herramienta', fr: 'Ouvrir l’outil', de: 'Tool öffnen', tr: 'Aracı aç', ru: 'Открыть инструмент', hi: 'टूल खोलें', zh: '打开工具' },
  'أضف الفيديو، اضبط الإعدادات، ثم صدّر النتيجة.': { en: 'Add a video, adjust the settings, then export the result.', es: 'Añade un vídeo, ajusta la configuración y exporta el resultado.', fr: 'Ajoutez une vidéo, ajustez les réglages, puis exportez le résultat.', de: 'Video hinzufügen, Einstellungen anpassen und Ergebnis exportieren.', tr: 'Bir video ekleyin, ayarları yapın ve sonucu dışa aktarın.', ru: 'Добавьте видео, настройте параметры и экспортируйте результат.', hi: 'वीडियो जोड़ें, सेटिंग्स समायोजित करें, फिर परिणाम निर्यात करें।', zh: '添加视频、调整设置，然后导出结果。' },
  'أضف الملف الصوتي، اختر المعالجة، ثم احفظ الناتج.': { en: 'Add an audio file, choose the processing, then save the output.', es: 'Añade un archivo de audio, elige el procesamiento y guarda el resultado.', fr: 'Ajoutez un fichier audio, choisissez le traitement, puis enregistrez le résultat.', de: 'Audiodatei hinzufügen, Verarbeitung auswählen und Ausgabe speichern.', tr: 'Bir ses dosyası ekleyin, işlemi seçin ve çıktıyı kaydedin.', ru: 'Добавьте аудиофайл, выберите обработку и сохраните результат.', hi: 'ऑडियो फ़ाइल जोड़ें, प्रोसेसिंग चुनें और आउटपुट सेव करें।', zh: '添加音频文件、选择处理方式，然后保存输出。' },
  'ارفع الصورة، عدّل أو عالجها، ثم نزّل النسخة النهائية.': { en: 'Upload an image, edit or process it, then download the final version.', es: 'Sube una imagen, edítala o procésala y descarga la versión final.', fr: 'Importez une image, retouchez-la ou traitez-la, puis téléchargez la version finale.', de: 'Bild hochladen, bearbeiten oder verarbeiten und finale Version herunterladen.', tr: 'Bir görsel yükleyin, düzenleyin veya işleyin, ardından son sürümü indirin.', ru: 'Загрузите изображение, отредактируйте или обработайте его, затем скачайте итоговую версию.', hi: 'इमेज अपलोड करें, उसे एडिट या प्रोसेस करें, फिर अंतिम वर्ज़न डाउनलोड करें।', zh: '上传图像、编辑或处理，然后下载最终版本。' },
  'اختر المستند أو الملفات، رتّب الإعدادات، ثم صدّر الملف.': { en: 'Choose a document or files, configure the settings, then export the file.', es: 'Elige un documento o archivos, configura los ajustes y exporta el archivo.', fr: 'Choisissez un document ou des fichiers, réglez les paramètres, puis exportez le fichier.', de: 'Dokument oder Dateien auswählen, Einstellungen festlegen und Datei exportieren.', tr: 'Bir belge veya dosyaları seçin, ayarları yapılandırın ve dosyayı dışa aktarın.', ru: 'Выберите документ или файлы, настройте параметры и экспортируйте файл.', hi: 'दस्तावेज़ या फ़ाइलें चुनें, सेटिंग्स कॉन्फ़िगर करें और फ़ाइल निर्यात करें।', zh: '选择文档或文件，配置设置，然后导出文件。' },
  'أدخل النص، اختر العملية، وانسخ أو نزّل النتيجة.': { en: 'Enter text, choose an operation, then copy or download the result.', es: 'Introduce texto, elige una operación y copia o descarga el resultado.', fr: 'Saisissez le texte, choisissez une opération, puis copiez ou téléchargez le résultat.', de: 'Text eingeben, Vorgang auswählen und Ergebnis kopieren oder herunterladen.', tr: 'Metni girin, bir işlem seçin, ardından sonucu kopyalayın veya indirin.', ru: 'Введите текст, выберите операцию, затем скопируйте или скачайте результат.', hi: 'टेक्स्ट दर्ज करें, ऑपरेशन चुनें, फिर परिणाम कॉपी या डाउनलोड करें।', zh: '输入文本、选择操作，然后复制或下载结果。' },
  'أدخل المحتوى أو الملفات، أكمل الإجراء، ثم شارك النتيجة.': { en: 'Add content or files, complete the action, then share the result.', es: 'Añade contenido o archivos, completa la acción y comparte el resultado.', fr: 'Ajoutez du contenu ou des fichiers, terminez l’action, puis partagez le résultat.', de: 'Inhalte oder Dateien hinzufügen, Aktion abschließen und Ergebnis teilen.', tr: 'İçerik veya dosya ekleyin, işlemi tamamlayın ve sonucu paylaşın.', ru: 'Добавьте содержимое или файлы, завершите действие и поделитесь результатом.', hi: 'सामग्री या फ़ाइलें जोड़ें, कार्रवाई पूरी करें और परिणाम साझा करें।', zh: '添加内容或文件，完成操作后分享结果。' }
};
