type TextFilterTranslationRow = Record<string, string>;

/** النصوص عالية الظهور في مصفاة النصوص؛ لا تشمل URLs أو صيغ Base64 التقنية. */
export const reviewedTextFilterText: Record<string, TextFilterTranslationRow> = {
  'مِصفاة النصوص الذكية': { en: 'Smart Text Filter', es: 'Filtro de texto inteligente', fr: 'Filtre de texte intelligent', de: 'Intelligenter Textfilter', tr: 'Akıllı Metin Filtresi', ru: 'Умный фильтр текста', hi: 'स्मार्ट टेक्स्ट फ़िल्टर', zh: '智能文本筛选器' },
  'استخرج البيانات ونظّف النصوص تدريجياً ورمّز العبارات بسرعة.': { en: 'Extract data, clean text progressively, and encode phrases quickly.', es: 'Extrae datos, limpia texto de forma progresiva y codifica frases rápidamente.', fr: 'Extrayez des données, nettoyez progressivement le texte et encodez des phrases rapidement.', de: 'Daten extrahieren, Text schrittweise bereinigen und Phrasen schnell kodieren.', tr: 'Verileri çıkarın, metni aşamalı olarak temizleyin ve ifadeleri hızla kodlayın.', ru: 'Извлекайте данные, постепенно очищайте текст и быстро кодируйте фразы.', hi: 'डेटा निकालें, टेक्स्ट को धीरे-धीरे साफ़ करें और वाक्यांशों को जल्दी एन्कोड करें।', zh: '提取数据、逐步清理文本并快速编码短语。' },
  'المدخلات': { en: 'Input', es: 'Entrada', fr: 'Entrée', de: 'Eingabe', tr: 'Girdi', ru: 'Ввод', hi: 'इनपुट', zh: '输入' },
  'توسيع': { en: 'Expand', es: 'Ampliar', fr: 'Agrandir', de: 'Erweitern', tr: 'Genişlet', ru: 'Развернуть', hi: 'विस्तृत करें', zh: '展开' },
  'طي': { en: 'Collapse', es: 'Contraer', fr: 'Réduire', de: 'Einklappen', tr: 'Daralt', ru: 'Свернуть', hi: 'समेटें', zh: '收起' },
  'ألصق مقالاً أو نصاً يحتوي روابط أو رسائل بريد أو مسافات زائدة أو رموزاً تعبيرية…': { en: 'Paste an article or text with links, emails, extra spaces, or emoji…', es: 'Pega un artículo o texto con enlaces, correos, espacios adicionales o emojis…', fr: 'Collez un article ou du texte avec des liens, des e-mails, des espaces superflus ou des émojis…', de: 'Artikel oder Text mit Links, E-Mails, zusätzlichen Leerzeichen oder Emojis einfügen…', tr: 'Bağlantılar, e-postalar, fazla boşluklar veya emojiler içeren bir makale ya da metin yapıştırın…', ru: 'Вставьте статью или текст со ссылками, e-mail, лишними пробелами или эмодзи…', hi: 'लिंक, ईमेल, अतिरिक्त स्पेस या इमोजी वाला लेख या टेक्स्ट पेस्ट करें…', zh: '粘贴包含链接、电子邮件、多余空格或表情符号的文章或文本…' },
  'استخراج وعزل البيانات': { en: 'Extract and isolate data', es: 'Extraer y aislar datos', fr: 'Extraire et isoler des données', de: 'Daten extrahieren und isolieren', tr: 'Verileri çıkar ve ayır', ru: 'Извлечь и выделить данные', hi: 'डेटा निकालें और अलग करें', zh: '提取并分离数据' },
  'عناوين البريد الإلكتروني': { en: 'Email addresses', es: 'Direcciones de correo', fr: 'Adresses e-mail', de: 'E-Mail-Adressen', tr: 'E-posta adresleri', ru: 'Адреса электронной почты', hi: 'ईमेल पते', zh: '电子邮件地址' },
  'الوسوم': { en: 'Hashtags', es: 'Etiquetas', fr: 'Hashtags', de: 'Hashtags', tr: 'Etiketler', ru: 'Хештеги', hi: 'हैशटैग', zh: '话题标签' },
  'تنظيف وتصفية العبارات': { en: 'Clean and filter text', es: 'Limpiar y filtrar texto', fr: 'Nettoyer et filtrer le texte', de: 'Text bereinigen und filtern', tr: 'Metni temizle ve filtrele', ru: 'Очистить и отфильтровать текст', hi: 'टेक्स्ट साफ़ और फ़िल्टर करें', zh: '清理和筛选文本' },
  'تفعيل تراكمي': { en: 'Cumulative mode', es: 'Modo acumulativo', fr: 'Mode cumulatif', de: 'Kumulativer Modus', tr: 'Birikimli mod', ru: 'Накопительный режим', hi: 'संचयी मोड', zh: '累计模式' },
  'تفريغ الصناديق': { en: 'Clear fields', es: 'Vaciar campos', fr: 'Vider les champs', de: 'Felder leeren', tr: 'Alanları temizle', ru: 'Очистить поля', hi: 'फ़ील्ड साफ़ करें', zh: '清空字段' },
  'الترميز وبايتات الخصوصية': { en: 'Encoding and privacy', es: 'Codificación y privacidad', fr: 'Encodage et confidentialité', de: 'Kodierung und Datenschutz', tr: 'Kodlama ve gizlilik', ru: 'Кодирование и конфиденциальность', hi: 'एन्कोडिंग और गोपनीयता', zh: '编码和隐私' },
  'اختر فلاتر التنظيف…': { en: 'Choose cleaning filters…', es: 'Elige filtros de limpieza…', fr: 'Choisissez des filtres de nettoyage…', de: 'Bereinigungsfilter auswählen…', tr: 'Temizleme filtrelerini seçin…', ru: 'Выберите фильтры очистки…', hi: 'क्लीनिंग फ़िल्टर चुनें…', zh: '选择清理筛选器…' },
  'إزالة الرموز التعبيرية': { en: 'Remove emoji', es: 'Eliminar emojis', fr: 'Supprimer les émojis', de: 'Emojis entfernen', tr: 'Emojileri kaldır', ru: 'Удалить эмодзи', hi: 'इमोजी हटाएँ', zh: '移除表情符号' },
  'إزالة الأسطر الفارغة': { en: 'Remove empty lines', es: 'Eliminar líneas vacías', fr: 'Supprimer les lignes vides', de: 'Leere Zeilen entfernen', tr: 'Boş satırları kaldır', ru: 'Удалить пустые строки', hi: 'खाली पंक्तियाँ हटाएँ', zh: '移除空行' },
  'المخرجات والنتائج الصافية': { en: 'Output and clean results', es: 'Salida y resultados limpios', fr: 'Résultats et sortie nettoyés', de: 'Ausgabe und bereinigte Ergebnisse', tr: 'Çıktı ve temiz sonuçlar', ru: 'Вывод и очищенные результаты', hi: 'आउटपुट और साफ़ परिणाम', zh: '输出和清理后的结果' },
  'ستظهر النتائج المصفّاة هنا تلقائياً…': { en: 'Filtered results will appear here automatically…', es: 'Los resultados filtrados aparecerán aquí automáticamente…', fr: 'Les résultats filtrés apparaîtront ici automatiquement…', de: 'Gefilterte Ergebnisse werden hier automatisch angezeigt…', tr: 'Filtrelenmiş sonuçlar burada otomatik olarak görünür…', ru: 'Отфильтрованные результаты появятся здесь автоматически…', hi: 'फ़िल्टर किए गए परिणाम यहाँ अपने-आप दिखाई देंगे…', zh: '筛选结果将自动显示在此处…' },
  'نسخ النتيجة الصافية فوراً': { en: 'Copy clean result', es: 'Copiar resultado limpio', fr: 'Copier le résultat nettoyé', de: 'Bereinigtes Ergebnis kopieren', tr: 'Temiz sonucu kopyala', ru: 'Копировать очищенный результат', hi: 'साफ़ परिणाम कॉपी करें', zh: '复制清理后的结果' },
  'تم تطبيق فلاتر التنظيف النشطة.': { en: 'Active cleaning filters applied.', es: 'Se aplicaron los filtros de limpieza activos.', fr: 'Les filtres de nettoyage actifs ont été appliqués.', de: 'Aktive Bereinigungsfilter angewendet.', tr: 'Etkin temizleme filtreleri uygulandı.', ru: 'Активные фильтры очистки применены.', hi: 'सक्रिय क्लीनिंग फ़िल्टर लागू हो गए।', zh: '已应用启用的清理筛选器。' },
  'تمت عملية الترميز محلياً.': { en: 'Encoding completed locally.', es: 'La codificación se completó de forma local.', fr: 'L’encodage est terminé localement.', de: 'Kodierung lokal abgeschlossen.', tr: 'Kodlama yerel olarak tamamlandı.', ru: 'Кодирование завершено локально.', hi: 'एन्कोडिंग स्थानीय रूप से पूरी हुई।', zh: '编码已在本地完成。' },
  'ترميز Base64': { en: 'Base64 encode', es: 'Codificar Base64', fr: 'Encoder en Base64', de: 'Base64 kodieren', tr: 'Base64 kodla', ru: 'Кодировать Base64', hi: 'Base64 एन्कोड करें', zh: 'Base64 编码' },
  'فك ترميز Base64': { en: 'Base64 decode', es: 'Decodificar Base64', fr: 'Décoder le Base64', de: 'Base64 dekodieren', tr: 'Base64 kodunu çöz', ru: 'Декодировать Base64', hi: 'Base64 डिकोड करें', zh: 'Base64 解码' }
};
