import { fetchFile } from '@ffmpeg/util';
import { getFFmpeg } from '@shared/runtime/ffmpeg';
import { toolBySlug } from '@shared/tools';
import { bootstrapStandaloneTool } from '@shared/ui/standalone-tool';
import { enhanceNativeSelect } from '@shared/ui/arsenal-select';
import { t } from '@shared/i18n';
import './video-compressor.css';

void bootstrapStandaloneTool('video-compressor', (shell) => {
  if (!toolBySlug('video-compressor')) throw new Error('تعذر العثور على تعريف ضاغط الفيديو.');
  shell.content.innerHTML = `
    <div class="vcm-page">
      <header class="vcm-header"><span class="vcm-header-icon"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"></polygon><rect x="1" y="5" width="15" height="14" rx="2"></rect></svg></span><div><h1 class="vcm-title">${t('ضاغط الفيديو الذكي')}</h1><p class="vcm-sub">${t('ضغط احترافي متعدد الأنوية عبر FFmpeg — محلي بالكامل بعد التحميل الأول.')}</p></div></header>
      <section class="vcm-section"><label id="vcm-upload" class="vcm-card vcm-drop-zone" for="vcm-file"><span class="vcm-drop-icon"><svg width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"></polygon><rect x="1" y="5" width="15" height="14" rx="2"></rect></svg></span><span id="vcm-upload-text" class="vcm-drop-text">${t('اضغط أو اسحب ملف الفيديو هنا')}</span><span id="vcm-upload-waiting" class="vcm-drop-text" hidden>${t('اختر ملف فيديو من جهازك…')}</span><span id="vcm-upload-loading" class="vcm-drop-text" hidden>${t('جاري قراءة الملف…')}</span><span id="vcm-file-meta" class="vcm-drop-meta" hidden></span><input id="vcm-file" type="file" accept="video/*"></label></section>
      <section class="vcm-section"><p class="vcm-section-label">${t('إعدادات الضغط')}</p><div class="vcm-card vcm-settings-card"><label class="vcm-setting-row"><span>${t('الدقة:')}</span><select id="vcm-resolution"><option value="original">${t('الأصلية — الحفاظ على أبعاد الملف')}</option><option value="1080">1080p — Full HD</option><option value="720">720p — HD</option><option value="480">480p — SD</option><option value="360">${t('360p — منخفضة')}</option></select></label><label class="vcm-setting-row"><span>${t('جودة الصورة:')}</span><select id="vcm-crf"><option value="18">${t('عالية جداً — حجم أكبر')}</option><option value="23">${t('عالية — متوازنة')}</option><option value="28" selected>${t('متوازنة — موصى بها')}</option><option value="33">${t('ضغط أقوى — حجم أصغر')}</option><option value="38">${t('اقتصادية — أقل جودة')}</option></select></label><label class="vcm-setting-row"><span>${t('سرعة الضغط:')}</span><select id="vcm-preset"><option value="ultrafast">${t('فائقة السرعة')}</option><option value="superfast">${t('سريعة جداً')}</option><option value="veryfast" selected>${t('سريعة')}</option><option value="fast">${t('سريعة محسّنة')}</option><option value="medium">${t('متوازنة')}</option><option value="slow">${t('بطيئة')}</option><option value="veryslow">${t('بطيئة جداً')}</option><option value="auto">${t('تلقائية حسب الدقة')}</option></select></label><label class="vcm-setting-row"><span>${t('عدد الأنوية:')}</span><select id="vcm-threads"><option value="auto" selected>${t('تلقائي — مريح للهاتف')}</option><option value="2">${t('نواتان')}</option><option value="4">${t('4 أنوية')}</option><option value="6">${t('6 أنوية')}</option><option value="8">${t('8 أنوية')}</option><option value="max-2">${t('الحد الآمن')}</option></select></label></div></section>
      <section class="vcm-section"><button id="vcm-start" class="vcm-btn vcm-btn-primary" type="button" disabled><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg><span>${t('ابدأ الضغط')}</span></button></section>
      <section id="vcm-status-wrap" class="vcm-section" hidden><div class="vcm-card vcm-status-card"><div class="vcm-status-header"><strong id="vcm-status-text">${t('جاري التهيئة…')}</strong><span id="vcm-status-percent">0%</span></div><div class="vcm-progress-track"><i id="vcm-progress"></i></div><div id="vcm-stats" class="vcm-stats" hidden><div><span>${t('الحجم الأصلي')}</span><b id="vcm-original-size">—</b></div><div><span>${t('الحجم الجديد')}</span><b id="vcm-new-size" class="vcm-green">—</b></div><div class="vcm-stat-full"><span>${t('نسبة التوفير')}</span><b id="vcm-saved" class="vcm-accent">—</b></div></div></div></section>
      <section id="vcm-download-wrap" class="vcm-section" hidden><button id="vcm-download" class="vcm-btn vcm-btn-success" type="button"><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg><span>${t('تحميل الفيديو المضغوط')}</span></button></section>
    </div>`;
  const $ = <T extends Element>(selector: string) => required<T>(shell.content, selector);
  const upload = $<HTMLElement>('#vcm-upload'), input = $<HTMLInputElement>('#vcm-file'), uploadText = $<HTMLElement>('#vcm-upload-text'), uploadWaiting = $<HTMLElement>('#vcm-upload-waiting'), uploadLoading = $<HTMLElement>('#vcm-upload-loading'), meta = $<HTMLElement>('#vcm-file-meta'), resolution = $<HTMLSelectElement>('#vcm-resolution'), crf = $<HTMLSelectElement>('#vcm-crf'), preset = $<HTMLSelectElement>('#vcm-preset'), threads = $<HTMLSelectElement>('#vcm-threads'), start = $<HTMLButtonElement>('#vcm-start'), statusWrap = $<HTMLElement>('#vcm-status-wrap'), statusText = $<HTMLElement>('#vcm-status-text'), statusPercent = $<HTMLElement>('#vcm-status-percent'), progress = $<HTMLElement>('#vcm-progress'), stats = $<HTMLElement>('#vcm-stats'), originalSize = $<HTMLElement>('#vcm-original-size'), newSize = $<HTMLElement>('#vcm-new-size'), saved = $<HTMLElement>('#vcm-saved'), downloadWrap = $<HTMLElement>('#vcm-download-wrap'), download = $<HTMLButtonElement>('#vcm-download');
  enhanceNativeSelect(resolution, { accent: 'var(--accent)' });
  enhanceNativeSelect(crf, { accent: 'var(--accent)' });
  enhanceNativeSelect(preset, { accent: 'var(--accent)' });
  enhanceNativeSelect(threads, { accent: 'var(--accent)' });
  let file: File | null = null, output: Blob | null = null;
  const updateProgress = (value: number, text: string) => { const percent = Math.min(100, Math.max(0, Math.round(value))); statusWrap.hidden = false; statusText.textContent = text; progress.style.width = `${percent}%`; statusPercent.textContent = `${percent}%`; };
  const showWaiting = () => { if (file) return; uploadText.hidden = true; uploadLoading.hidden = true; uploadWaiting.hidden = false; };
  const restoreIdle = () => { if (file) return; uploadText.hidden = false; uploadWaiting.hidden = true; uploadLoading.hidden = true; };
  const choose = (next: File) => { output = null; upload.classList.remove('has-file'); upload.classList.add('loading'); uploadText.hidden = true; uploadWaiting.hidden = true; uploadLoading.hidden = false; meta.hidden = true; start.disabled = true; downloadWrap.hidden = true; statusWrap.hidden = true; stats.hidden = true; progress.style.width = '0%'; statusPercent.textContent = '0%'; window.requestAnimationFrame(() => { file = next; upload.classList.remove('loading'); upload.classList.add('has-file'); uploadLoading.hidden = true; uploadText.hidden = false; uploadText.textContent = next.name; meta.hidden = false; meta.textContent = formatBytes(next.size); start.disabled = false; shell.setStatus(t('الفيديو جاهز. يُحمّل محرك الضغط فقط عند الضغط على زر البدء.'), 'success'); }); };
  upload.addEventListener('click', showWaiting); input.addEventListener('cancel', restoreIdle); input.addEventListener('change', () => { const next = input.files?.[0]; if (next) choose(next); else restoreIdle(); });
  ['dragenter', 'dragover'].forEach((name) => upload.addEventListener(name, (event) => { event.preventDefault(); upload.classList.add('drag-active'); })); ['dragleave', 'drop'].forEach((name) => upload.addEventListener(name, (event) => { event.preventDefault(); upload.classList.remove('drag-active'); })); upload.addEventListener('drop', (event) => { const next = event.dataTransfer?.files[0]; if (next?.type.startsWith('video/')) choose(next); else shell.setStatus(t('اختر ملف فيديو صالحاً فقط.'), 'error'); });
  start.addEventListener('click', async () => { if (!file) return; start.disabled = true; output = null; downloadWrap.hidden = true; stats.hidden = true; updateProgress(3, t('جاري تحميل محرك الضغط…')); const stamp = Date.now(), inputName = `input-${stamp}.${extension(file.name)}`, outputName = `compressed-${stamp}.mp4`; try { const ffmpeg = await getFFmpeg((percent) => updateProgress(12 + percent * .85, t('يجري ضغط الفيديو: {percent}%', { percent }))); updateProgress(10, t('جاري قراءة الفيديو…')); await ffmpeg.writeFile(inputName, await fetchFile(file)); const dimensions = await getDimensions(file); const selectedThreads = safeThreads(threads.value), selectedPreset = smartPreset(preset.value, dimensions.width, dimensions.height); const args = ['-i', inputName]; if (resolution.value !== 'original') args.push('-vf', `scale=-2:${resolution.value}`); args.push('-c:v', 'libx264', '-threads', String(selectedThreads), '-preset', selectedPreset, '-crf', crf.value, '-c:a', 'aac', '-b:a', '128k', '-movflags', '+faststart', '-y', outputName); updateProgress(12, t('يجري ضغط الفيديو…')); await ffmpeg.exec(args); updateProgress(97, t('يجري تجهيز الملف النهائي…')); const data = await ffmpeg.readFile(outputName); if (!(data instanceof Uint8Array)) throw new Error(t('تعذر قراءة الفيديو الناتج.')); output = new Blob([data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength) as ArrayBuffer], { type: 'video/mp4' }); try { await ffmpeg.deleteFile(inputName); await ffmpeg.deleteFile(outputName); } catch { /* تنظيف اختياري */ } const difference = file.size - output.size, percentage = difference / file.size * 100; originalSize.textContent = formatBytes(file.size); newSize.textContent = formatBytes(output.size); saved.textContent = difference >= 0 ? t('{percent}% توفير', { percent: percentage.toFixed(1) }) : t('الحجم الأصلي أصغر'); stats.hidden = false; downloadWrap.hidden = false; updateProgress(100, t('اكتمل الضغط')); shell.setStatus(t('تم ضغط الفيديو محلياً. يمكنك تنزيل الناتج الآن.'), 'success'); } catch (error) { console.error(error); updateProgress(0, t('تعذر ضغط الفيديو')); shell.setStatus(t('تعذر ضغط الفيديو: {reason}', { reason: error instanceof Error ? error.message.slice(0, 100) : t('خطأ غير متوقع') }), 'error'); } finally { start.disabled = false; } });
  download.addEventListener('click', () => { if (!output) return; const url = URL.createObjectURL(output), link = document.createElement('a'); link.href = url; link.download = `Arsenal_${file?.name.replace(/\.[^.]+$/, '') || 'video'}.mp4`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 900); });
});

function safeThreads(choice: string): number { const logical = navigator.hardwareConcurrency || 2, max = Math.max(1, logical - 1); if (choice === 'auto') return Math.min(4, max); if (choice === 'max-2') return Math.max(1, logical - 2); const value = Number(choice); return Number.isFinite(value) ? Math.min(value, max) : Math.max(1, Math.floor(logical / 2)); }
function smartPreset(choice: string, width: number, height: number): string { if (choice !== 'auto') return choice; const pixels = width * height; if (pixels >= 1920 * 1080) return 'veryfast'; if (pixels >= 1280 * 720) return 'superfast'; return 'ultrafast'; }
async function getDimensions(file: File): Promise<{ width: number; height: number }> { const video = document.createElement('video'), url = URL.createObjectURL(file); return new Promise((resolve) => { const done = () => { const result = { width: video.videoWidth || 1920, height: video.videoHeight || 1080 }; URL.revokeObjectURL(url); resolve(result); }; video.onloadedmetadata = done; video.onerror = done; video.src = url; window.setTimeout(done, 2000); }); }
function extension(name: string): string { return name.split('.').pop()?.replace(/[^a-z0-9]/gi, '') || 'mp4'; }
function formatBytes(bytes: number): string { if (!bytes) return '0 B'; const units = ['B','KB','MB','GB'], index = Math.floor(Math.log(bytes) / Math.log(1024)); return `${(bytes / Math.pow(1024, index)).toFixed(2)} ${units[index]}`; }
function required<T extends Element>(root: ParentNode, selector: string): T { const element = root.querySelector<T>(selector); if (!element) throw new Error(`العنصر المطلوب غير موجود: ${selector}`); return element; }
