import type { ToolDefinition } from './types/tool';

export const TOOLS: readonly ToolDefinition[] = [
  { slug: 'video-editor', id: 'gif_generator', category: 'video', icon: 'gif', accent: '#00d4aa', title: 'منشئ GIF', description: 'اقتطاع وتحويل الفيديوهات إلى GIF فورياً من المتصفح.', keywords: ['فيديو', 'gif', 'تحويل', 'قص', 'فيديو إلى GIF'], legacyPath: '/video/video_editor/video_editor.html' },
  { slug: 'video-compressor', id: 'video_compressor', category: 'video', icon: 'video-compress', accent: '#00d4aa', title: 'ضاغط الفيديو', description: 'ضغط الفيديو بإعدادات جودة ودقة وأداء قابلة للتحكم.', keywords: ['فيديو', 'ضغط', 'mp4', 'video'], legacyPath: '/video/video_compressor/video_compressor.html' },
  { slug: 'video-to-audio', id: 'video_converter_f_voice', category: 'video', icon: 'video-audio', accent: '#00d4aa', title: 'فيديو إلى صوت', description: 'استخراج المسار الصوتي من ملف فيديو محلياً.', keywords: ['فيديو', 'صوت', 'mp3', 'audio'], legacyPath: '/video/video_converter_f_voice/video_converter_f_voice.html' },
  { slug: 'audio-converter', id: 'audio_adapter', category: 'audio', icon: 'waveform', accent: '#f5a623', title: 'محول الصوت', description: 'تحويل صيغ الملفات الصوتية بصورة مستقلة.', keywords: ['صوت', 'تحويل', 'wav', 'mp3'], legacyPath: '/audio/audio_adapter/audio_adapter.html' },
  { slug: 'noise-remover', id: 'noise_remover', category: 'audio', icon: 'noise', accent: '#f5a623', title: 'مزيل الضوضاء', description: 'تنقية الصوت بالذكاء الاصطناعي داخل المتصفح.', keywords: ['صوت', 'ضوضاء', 'ذكاء اصطناعي'], legacyPath: '/audio/noise_remover/noise_remover.html' },
  { slug: 'audio-rate', id: 'audio_rate', category: 'audio', icon: 'clock', accent: '#f5a623', title: 'معدل الصوت', description: 'تغيير سرعة الصوت وتصديره كملف جديد.', keywords: ['صوت', 'سرعة', 'تبطيء'], legacyPath: '/audio/audio_rate/audio_rate.html' },
  { slug: 'image-editor', id: 'image_editor', category: 'image', icon: 'image', accent: '#ff5f68', title: 'محرر الصور', description: 'تعديلات أساسية للصور عبر مساحة عمل محلية.', keywords: ['صورة', 'تحرير', 'image'], legacyPath: '/image/image_editor/image_editor.html' },
  { slug: 'background-remover', id: 'image_remover', category: 'image', icon: 'cutout', accent: '#ff5f68', title: 'مزيل الخلفية', description: 'عزل الخلفية ومعالجة الصورة محلياً.', keywords: ['صورة', 'خلفية', 'عزل'], legacyPath: '/image/image_remover/image_remover.html' },
  { slug: 'image-compressor', id: 'image_compressor', category: 'image', icon: 'image-compress', accent: '#ff5f68', title: 'ضاغط الصور', description: 'ضغط صور متعددة مع تنزيل النتيجة.', keywords: ['صورة', 'ضغط', 'png', 'jpg'], legacyPath: '/image/image_compressor/image_compressor.html' },
  { slug: 'pdf-create', id: 'pdf_create', category: 'pdf', icon: 'file-plus', accent: '#a855f7', title: 'إنشاء PDF', description: 'تكوين مستند PDF من عناصر ومحتوى محلي.', keywords: ['pdf', 'إنشاء', 'مستند'], legacyPath: '/pdf/pdf_create/pdf_create.html' },
  { slug: 'pdf-compressor', id: 'pdf_compressor', category: 'pdf', icon: 'file-down', accent: '#a855f7', title: 'ضاغط PDF', description: 'تقليل حجم مستند PDF محلياً.', keywords: ['pdf', 'ضغط', 'مستند'], legacyPath: '/pdf/pdf_compressor/pdf_compressor.html' },
  { slug: 'pdf-editor', id: 'pdf_editor', category: 'pdf', icon: 'file-edit', accent: '#a855f7', title: 'محرر PDF', description: 'تحميل واستعراض وتعديل مستندات PDF.', keywords: ['pdf', 'تحرير', 'مستند'], legacyPath: '/pdf/pdf_editor/pdf_editor.html' },
  { slug: 'text-encryption', id: 'encrypted_texts', category: 'text', icon: 'lock', accent: '#2eb7ef', title: 'تشفير النصوص', description: 'تشفير وفك تشفير النصوص محلياً.', keywords: ['نص', 'تشفير', 'aes'], legacyPath: '/text/encrypted_texts/encrypted_texts.html' },
  { slug: 'text-filter', id: 'text_filter', category: 'text', icon: 'filter', accent: '#2eb7ef', title: 'مِصفاة النصوص', description: 'تنسيق وترميز وتحويل النصوص.', keywords: ['نص', 'base64', 'تنسيق'], legacyPath: '/text/text_filter/text_filter.html' },
  { slug: 'text-comparison', id: 'text_comparison', category: 'text', icon: 'compare', accent: '#2eb7ef', title: 'مقارنة النصوص', description: 'إظهار الفروقات بين نصين محلياً.', keywords: ['نص', 'مقارنة', 'فرق'], legacyPath: '/text/text_comparison/text_comparison.html' },
  { slug: 'qr-generator', id: 'qr_generator', category: 'utility', icon: 'qr', accent: '#00d4aa', title: 'مولد QR', description: 'إنشاء رمز QR قابل للتنزيل.', keywords: ['qr', 'رمز', 'مشاركة'], legacyPath: '/multi_tools_library/qr_generator/qr_generator.html' },
  { slug: 'archive-encryption', id: 'arsenal_archive', category: 'utility', icon: 'archive', accent: '#00d4aa', title: 'الأرشفة والتشفير', description: 'إنشاء أرشيفات ZIP وتشفيرها محلياً.', keywords: ['zip', 'أرشيف', 'تشفير'], legacyPath: '/multi_tools_library/archive/arsenal_archive.html' },
  { slug: 'local-share', id: 'arsenal_share', category: 'utility', icon: 'share', accent: '#00d4aa', title: 'المشاركة المحلية', description: 'مشاركة الملفات بين الأجهزة على الشبكة المحلية.', keywords: ['مشاركة', 'ملفات', 'محلي'], legacyPath: '/multi_tools_library/arsenal_share/arsenal_share.html' }
] as const;

export const toolBySlug = (slug: string): ToolDefinition | undefined => TOOLS.find((tool) => tool.slug === slug);
