import { bootstrapStandaloneTool } from '@shared/ui/standalone-tool';
import { toolBySlug } from '@shared/tools';
import { iconSvg } from '@shared/ui/icons';
import { t } from '@shared/i18n';
import './image-compressor.css';

type QueueItem = { id:number; file:File; status:'pending'|'processing'|'done'|'error'; blob:Blob|null; newSize:number };

void bootstrapStandaloneTool('image-compressor', (shell) => {
  if (!toolBySlug('image-compressor')) throw new Error('تعذر العثور على تعريف ضاغط الصور.');
  shell.content.innerHTML = `
    <div class="imc-page">
      <header class="imc-header"><span class="imc-header-icon"><svg width="27" height="27" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="17 8 12 3 7 8"></polyline><line x1="12" y1="3" x2="12" y2="15"></line></svg></span><div><h1>${t('ضاغط الصور')}</h1><p>${t('ضغط صور دفعي محلياً بالكامل ومن دون إنترنت.')}</p></div></header>
      <section class="imc-section"><p class="imc-section-label">${t('الملفات')}</p><label id="imc-drop" class="imc-card imc-drop-zone" for="imc-files"><span class="imc-drop-icon"><svg width="33" height="33" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg></span><b id="imc-drop-text">${t('اضغط هنا لاختيار الصور')}</b><span>${t('JPG · PNG · WEBP — يمكن اختيار عدة صور')}</span><input id="imc-files" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><div class="imc-folder-row"><span>${t('أو')}</span><button id="imc-folder-button" class="imc-folder-btn" type="button">${iconSvg('folder','imc-folder-icon')} ${t('اختر مجلداً كاملاً')}</button><input id="imc-folder" type="file" multiple></div></section>
      <section id="imc-queue" class="imc-summary" hidden></section>
      <section class="imc-section"><p class="imc-section-label">${t('مستوى الجودة')}</p><div class="imc-card imc-quality-card"><div class="imc-ctrl-row"><span>${t('جودة الصورة')}</span><b id="imc-quality-value">80%</b></div><input id="imc-quality" class="imc-slider" type="range" min="10" max="100" value="80"><div class="imc-slider-marks"><span>10%</span><span>30%</span><span>50%</span><span>70%</span><span>100%</span></div><p>${t('كلما زادت النسبة، زادت الدقة وزاد حجم الملف.')}</p></div></section>
      <section id="imc-progress-section" class="imc-section" hidden><div class="imc-card"><p id="imc-progress-text" class="imc-progress-text">${t('جاري التحضير…')}</p><div class="imc-progress-track"><div id="imc-progress-fill" class="imc-progress-fill"></div></div></div></section>
      <section class="imc-section"><button id="imc-compress" class="imc-action imc-compress" type="button" disabled>${iconSvg('sparkles','imc-compress-icon')}<span id="imc-compress-text">${t('اضغط كل الصور الآن')}</span></button></section>
      <section id="imc-download-section" class="imc-section" hidden><button id="imc-download" class="imc-action imc-download" type="button"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg><span id="imc-download-text">${t('تنزيل الكل (ZIP)')}</span></button></section>
    </div>`;
  const $=<T extends Element>(selector:string)=>required<T>(shell.content,selector);const drop=$<HTMLElement>('#imc-drop'),dropText=$<HTMLElement>('#imc-drop-text'),files=$<HTMLInputElement>('#imc-files'),folder=$<HTMLInputElement>('#imc-folder'),folderButton=$<HTMLButtonElement>('#imc-folder-button'),queueEl=$<HTMLElement>('#imc-queue'),quality=$<HTMLInputElement>('#imc-quality'),qualityValue=$<HTMLElement>('#imc-quality-value'),compress=$<HTMLButtonElement>('#imc-compress'),compressText=$<HTMLElement>('#imc-compress-text'),progressSection=$<HTMLElement>('#imc-progress-section'),progressText=$<HTMLElement>('#imc-progress-text'),progressFill=$<HTMLElement>('#imc-progress-fill'),downloadSection=$<HTMLElement>('#imc-download-section'),download=$<HTMLButtonElement>('#imc-download'),downloadText=$<HTMLElement>('#imc-download-text');folder.setAttribute('webkitdirectory','');folder.setAttribute('directory','');
  let queue:QueueItem[]=[];let id=0;let running=false;
  const allowed=(file:File)=>file.type==='image/jpeg'||file.type==='image/png'||file.type==='image/webp';
  const updateQuality=()=>{qualityValue.textContent=`${quality.value}%`;const percent=(Number(quality.value)-10)/90*100;quality.style.background=`linear-gradient(90deg,var(--accent) 0 ${percent}%,var(--surface-strong) ${percent}% 100%)`;};
  const renderQueue=()=>{if(!queue.length){queueEl.hidden=true;compress.disabled=true;return;}const total=queue.reduce((sum,item)=>sum+item.file.size,0),done=queue.filter((item)=>item.status==='done'),compressed=done.reduce((sum,item)=>sum+item.newSize,0),saved=compressed?Math.round((1-compressed/total)*100):0;queueEl.hidden=false;queueEl.innerHTML=`<div class="imc-summary-row"><div><span>${t('الملفات')}</span><b>${t('{count} صورة', { count: queue.length })}</b></div><div><span>${t('الحجم الأصلي')}</span><b>${formatBytes(total)}</b></div>${done.length?`<div><span>${t('بعد الضغط')}</span><b class="imc-good">${formatBytes(compressed)}</b></div><div><span>${t('وفّرت')}</span><b class="imc-percent">${saved}%</b></div>`:''}</div><p class="imc-summary-hint">${done.length?t('تمت معالجة {done} من {total} صورة.', { done: done.length, total: queue.length }):t('اضغط «اضغط كل الصور الآن» لبدء المعالجة.')}</p>`;compress.disabled=running||!queue.some((item)=>item.status==='pending'||item.status==='error');};
  const addFiles=(incoming:File[])=>{const accepted=incoming.filter(allowed);if(!accepted.length){shell.setStatus(t('لم تُضف أي صورة متوافقة. يقبل الضاغط JPG وPNG وWEBP فقط.'),'error');return;}queue.push(...accepted.map((file)=>({id:id+=1,file,status:'pending' as const,blob:null,newSize:0})));drop.classList.add('has-files');dropText.textContent=t('تم تحديد {count} صورة — اضغط لإضافة المزيد', { count: queue.length });downloadSection.hidden=true;renderQueue();shell.setStatus(t('أضيفت {count} صورة إلى قائمة الضغط.', { count: accepted.length }),'success');};
  const imageFiles=()=>Array.from(files.files||[]);files.addEventListener('change',()=>{addFiles(imageFiles());files.value='';});folder.addEventListener('change',()=>{addFiles(Array.from(folder.files||[]));folder.value='';});folderButton.addEventListener('click',()=>folder.click());['dragenter','dragover'].forEach((name)=>drop.addEventListener(name,(event)=>{event.preventDefault();drop.classList.add('drag-active');}));['dragleave','drop'].forEach((name)=>drop.addEventListener(name,(event)=>{event.preventDefault();drop.classList.remove('drag-active');}));drop.addEventListener('drop',(event)=>addFiles(Array.from(event.dataTransfer?.files||[])));quality.addEventListener('input',updateQuality);updateQuality();
  const compressOne=async(file:File,qualityPercent:number):Promise<Blob>=>{const image=await imageFromFile(file),canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const context=canvas.getContext('2d');if(!context)throw new Error('Canvas غير متاح.');context.drawImage(image,0,0);return new Promise((resolve,reject)=>canvas.toBlob((blob)=>blob?resolve(blob):reject(new Error('تعذر ترميز الصورة.')),'image/jpeg',qualityPercent/100));};
  compress.addEventListener('click',async()=>{if(running||!queue.length)return;const pending=queue.filter((item)=>item.status==='pending'||item.status==='error');if(!pending.length)return;running=true;compress.disabled=true;compressText.textContent=t('جاري الضغط…');progressSection.hidden=false;downloadSection.hidden=true;progressFill.style.width='0%';let finished=0;for(const item of pending){item.status='processing';progressText.textContent=t('جاري المعالجة: {current} من {total}', { current: finished + 1, total: pending.length });renderQueue();try{item.blob=await compressOne(item.file,Number(quality.value));item.newSize=item.blob.size;item.status='done';}catch(error){item.status='error';shell.setStatus(t('تعذر ضغط {name}: {reason}', { name: item.file.name, reason: error instanceof Error ? error.message : t('خطأ غير متوقع') }),'error');}finished+=1;progressFill.style.width=`${Math.round(finished/pending.length*100)}%`;renderQueue();await new Promise((resolve)=>window.setTimeout(resolve,0));}running=false;compressText.textContent=t('اضغط كل الصور الآن');progressText.textContent=t('اكتمل الضغط بنجاح');renderQueue();const success=queue.filter((item)=>item.status==='done').length;if(success){downloadSection.hidden=false;shell.setStatus(t('اكتمل ضغط {count} صورة محلياً. يمكنك تنزيلها في ZIP.', { count: success }),'success');}});
  download.addEventListener('click',async()=>{const done=queue.filter((item)=>item.status==='done'&&item.blob);if(!done.length)return;download.disabled=true;downloadText.textContent=t('جاري إنشاء ZIP…');try{const {default:JSZip}=await import('jszip');const zip=new JSZip();for(const item of done){const stem=item.file.name.replace(/\.[^.]+$/,'');zip.file(`${stem}_compressed.jpg`,item.blob as Blob);}const blob=await zip.generateAsync({type:'blob'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='Arsenal_Compressed_Images.zip';link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);shell.setStatus(t('أصبح ملف ZIP جاهزاً في التنزيلات.'),'success');}catch(error){shell.setStatus(t('تعذر إنشاء ZIP: {reason}', { reason: error instanceof Error ? error.message : t('خطأ غير متوقع') }),'error');}finally{download.disabled=false;downloadText.textContent=t('تنزيل الكل (ZIP)');}});
});
function required<T extends Element>(root:ParentNode,selector:string):T{const element=root.querySelector<T>(selector);if(!element)throw new Error(`العنصر المطلوب غير موجود: ${selector}`);return element;}function formatBytes(bytes:number):string{if(!bytes)return'0 B';const units=['B','KB','MB','GB'],index=Math.min(units.length-1,Math.floor(Math.log(bytes)/Math.log(1024)));return`${(bytes/1024**index).toFixed(index?2:0)} ${units[index]}`;}function imageFromFile(file:File):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve(image);};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('تعذر قراءة الصورة.'));};image.src=url;});}
