import { getLame } from '@shared/runtime/lame';
import { toolBySlug } from '@shared/tools';
import { bootstrapStandaloneTool } from '@shared/ui/standalone-tool';
import { enhanceNativeSelect } from '@shared/ui/arsenal-select';
import { t } from '@shared/i18n';
import './video-to-audio.css';

void bootstrapStandaloneTool('video-to-audio', (shell) => {
  if (!toolBySlug('video-to-audio')) throw new Error('تعذر العثور على تعريف مستخرج الصوت من الفيديو.');
  shell.content.innerHTML = `
    <div class="vcv-page">
      <header class="vcv-header"><span class="vcv-header-icon"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18V5l12-2v13"></path><circle cx="6" cy="18" r="3"></circle><circle cx="18" cy="16" r="3"></circle></svg></span><div><h1 class="vcv-title">${t('مستخرج الصوت من الفيديو')}</h1><p class="vcv-sub">${t('استخراج المسار الصوتي من أي فيديو وتحويله إلى WAV أو MP3 — محلياً وبدون إنترنت.')}</p></div></header>
      <section class="vcv-section"><p class="vcv-section-label">${t('ملف الفيديو')}</p><label id="vc-drop" class="vcv-drop-zone" for="vc-file"><span class="vcv-drop-icon"><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"></polygon><rect x="1" y="5" width="15" height="14" rx="2"></rect></svg></span><strong id="vc-file-label">${t('اضغط هنا لاختيار ملف الفيديو')}</strong><span>${t('يدعم MP4 وWebM وMOV وغيرها')}</span><input id="vc-file" type="file" accept="video/*"></label></section>
      <section id="vc-status" class="vcv-status" hidden><strong id="vc-status-text">${t('جاري المعالجة…')}</strong><div><i id="vc-status-bar"></i></div><span id="vc-status-percent">0%</span></section>
      <section id="vc-stats" class="vcv-stats" hidden><div><span>${t('حجم الفيديو')}</span><b id="vc-video-size" class="vcv-red">0 MB</b></div><div><span>${t('حجم الصوت المستخرج')}</span><b id="vc-audio-size" class="vcv-green">0 MB</b></div></section>
      <section id="vc-preview" class="vcv-section" hidden><button id="vc-play" class="vcv-btn vcv-btn-play" type="button" disabled><svg id="vc-play-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg><span id="vc-play-text">${t('تشغيل المعاينة')}</span></button><div id="vc-timeline" class="vcv-timeline"><span id="vc-current" class="vcv-time">00:00</span><div id="vc-track" class="vcv-track"><i id="vc-progress"></i><i id="vc-thumb"></i></div><span id="vc-total" class="vcv-time">00:00</span></div></section>
      <section id="vc-download-wrap" class="vcv-download" hidden><div><p class="vcv-section-label">${t('صيغة التصدير')}</p><label class="vcv-format"><select id="vc-format"><option value="wav" data-description="${t('خام ونقي 100٪')}">WAV</option><option value="mp3" data-description="${t('مضغوط وعالي التوافق')}">MP3</option></select></label></div><button id="vc-download" class="vcv-btn vcv-btn-success" type="button"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2 2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg><span id="vc-download-label">${t('تحميل ملف الصوت ({format})', { format: 'WAV' })}</span></button></section>
    </div>`;
  const $ = <T extends Element>(selector: string) => required<T>(shell.content, selector);
  const drop = $<HTMLElement>('#vc-drop'), input = $<HTMLInputElement>('#vc-file'), fileLabel = $<HTMLElement>('#vc-file-label'), status = $<HTMLElement>('#vc-status'), statusText = $<HTMLElement>('#vc-status-text'), statusBar = $<HTMLElement>('#vc-status-bar'), statusPercent = $<HTMLElement>('#vc-status-percent'), stats = $<HTMLElement>('#vc-stats'), videoSize = $<HTMLElement>('#vc-video-size'), audioSize = $<HTMLElement>('#vc-audio-size'), preview = $<HTMLElement>('#vc-preview'), play = $<HTMLButtonElement>('#vc-play'), playIcon = $<SVGElement>('#vc-play-icon'), playText = $<HTMLElement>('#vc-play-text'), timeline = $<HTMLElement>('#vc-timeline'), track = $<HTMLElement>('#vc-track'), progress = $<HTMLElement>('#vc-progress'), thumb = $<HTMLElement>('#vc-thumb'), current = $<HTMLElement>('#vc-current'), total = $<HTMLElement>('#vc-total'), downloadWrap = $<HTMLElement>('#vc-download-wrap'), format = $<HTMLSelectElement>('#vc-format'), download = $<HTMLButtonElement>('#vc-download'), downloadLabel = $<HTMLElement>('#vc-download-label');
  let formatSelectReady = false;
  const ensureFormatSelect = () => { if (formatSelectReady) return; enhanceNativeSelect(format, { accent: 'var(--accent-2)' }); formatSelectReady = true; };
  let sourceFile: File | null = null, audioBuffer: AudioBuffer | null = null, wav: Blob | null = null, context: AudioContext | null = null, source: AudioBufferSourceNode | null = null, playing = false, currentPosition = 0, startedAt = 0, frame: number | null = null, scrubbing = false;
  const duration = () => audioBuffer?.duration ?? 0;
  const setStatus = (percent: number, message: string) => { status.hidden = false; statusBar.style.width = `${percent}%`; statusPercent.textContent = `${Math.round(percent)}%`; statusText.textContent = message; };
  const setTimeline = (value: number) => { currentPosition = Math.max(0, Math.min(duration(), value)); const ratio = duration() ? currentPosition / duration() : 0; progress.style.width = `${ratio * 100}%`; thumb.style.left = `${ratio * 100}%`; current.textContent = formatTime(currentPosition); };
  const resetPlayer = () => { try { source?.stop(); } catch { /* المصدر منتهٍ */ } source?.disconnect(); source = null; void context?.close(); context = null; playing = false; if (frame !== null) cancelAnimationFrame(frame); frame = null; playIcon.innerHTML = '<polygon points="5 3 19 12 5 21 5 3"></polygon>'; playText.textContent = t('تشغيل المعاينة'); play.style.background = ''; };
  const select = async (file: File) => { sourceFile = file; fileLabel.textContent = t('جاري قراءة المسار الصوتي…'); drop.classList.add('is-loading'); status.hidden = false; stats.hidden = true; preview.hidden = true; downloadWrap.hidden = true; setStatus(10, t('جاري قراءة الفيديو…')); try { const data = await file.arrayBuffer(); setStatus(30, t('جاري فك ترميز المسار الصوتي…')); const decoder = new AudioContext(); audioBuffer = await decoder.decodeAudioData(data); await decoder.close(); setStatus(75, t('يجري إنشاء WAV…')); wav = encodeWav(audioBuffer); total.textContent = formatTime(audioBuffer.duration); setTimeline(0); fileLabel.textContent = file.name; drop.classList.remove('is-loading'); drop.classList.add('has-file'); videoSize.textContent = formatBytes(file.size); audioSize.textContent = formatBytes(wav.size); stats.hidden = false; preview.hidden = false; downloadWrap.hidden = false; window.requestAnimationFrame(ensureFormatSelect); play.disabled = false; setStatus(100, t('اكتمل استخراج المسار الصوتي')); window.setTimeout(() => { status.hidden = true; }, 650); shell.setStatus(t('تم استخراج الصوت محلياً. يمكنك معاينته أو تنزيله بصيغة WAV أو MP3.'), 'success'); } catch (error) { drop.classList.remove('is-loading'); fileLabel.textContent = t('تعذر استخراج صوت من هذا الفيديو'); status.hidden = true; shell.setStatus(t('تعذر استخراج الصوت: {reason}', { reason: error instanceof Error ? error.message : t('خطأ غير متوقع') }), 'error'); } };
  input.addEventListener('change', () => { const file = input.files?.[0]; if (file) void select(file); }); ['dragenter','dragover'].forEach((name) => drop.addEventListener(name, (event) => { event.preventDefault(); drop.classList.add('drag-active'); })); ['dragleave','drop'].forEach((name) => drop.addEventListener(name, (event) => { event.preventDefault(); drop.classList.remove('drag-active'); })); drop.addEventListener('drop', (event) => { const file = event.dataTransfer?.files[0]; if (file?.type.startsWith('video/')) void select(file); else shell.setStatus(t('اختر ملف فيديو صالحاً فقط.'), 'error'); });
  function tick(): void { if (!playing || !context) return; setTimeline(context.currentTime - startedAt); frame = requestAnimationFrame(tick); }
  function start(): void { if (!audioBuffer) return; resetPlayer(); context = new AudioContext(); source = context.createBufferSource(); source.buffer = audioBuffer; source.connect(context.destination); source.start(0, currentPosition); startedAt = context.currentTime - currentPosition; playing = true; playIcon.innerHTML = '<rect x="6" y="4" width="4" height="16"></rect><rect x="14" y="4" width="4" height="16"></rect>'; playText.textContent = t('إيقاف'); play.style.background = '#ff4b4b'; source.addEventListener('ended', () => { if (playing) { setTimeline(0); resetPlayer(); } }, { once:true }); tick(); }
  function stop(): void { if (context && playing) setTimeline(context.currentTime - startedAt); resetPlayer(); }
  play.addEventListener('click', () => playing ? stop() : start());
  const pointerRatio = (event: PointerEvent) => { const rect = track.getBoundingClientRect(); return Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)); }; timeline.addEventListener('pointerdown', (event) => { if (!audioBuffer) return; scrubbing = true; timeline.setPointerCapture(event.pointerId); timeline.classList.add('scrubbing'); if (playing) stop(); setTimeline(pointerRatio(event) * duration()); }); timeline.addEventListener('pointermove', (event) => { if (scrubbing) setTimeline(pointerRatio(event) * duration()); }); const endScrub = () => { scrubbing = false; timeline.classList.remove('scrubbing'); }; timeline.addEventListener('pointerup', endScrub); timeline.addEventListener('pointercancel', endScrub);
  format.addEventListener('change', () => { downloadLabel.textContent = t('تحميل ملف الصوت ({format})', { format: format.value.toUpperCase() }); });
  download.addEventListener('click', async () => { if (!audioBuffer || !wav) return; download.disabled = true; try { if (format.value === 'mp3') { setStatus(5, t('جاري تحميل ترميز MP3…')); const mp3 = await encodeMp3(audioBuffer, (value) => setStatus(value, t('يجري ترميز MP3: {percent}%', { percent: value }))); save(mp3, 'mp3'); } else save(wav, 'wav'); shell.setStatus(t('تم تنزيل ملف الصوت محلياً.'), 'success'); } catch (error) { shell.setStatus(t('تعذر إنشاء MP3: {reason}', { reason: error instanceof Error ? error.message : t('خطأ غير متوقع') }), 'error'); } finally { download.disabled = false; window.setTimeout(() => { status.hidden = true; }, 800); } });
  function save(blob: Blob, suffix: string): void { const url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = `Arsenal_${sourceFile?.name.replace(/\.[^.]+$/, '') || 'video'}_audio.${suffix}`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 900); }
});

async function encodeMp3(buffer: AudioBuffer, onProgress: (value: number) => void): Promise<Blob> { const lame = await getLame(); const channels = Math.min(2, buffer.numberOfChannels), encoder = new lame.Mp3Encoder(channels, buffer.sampleRate, 128), left = toInt16(buffer.getChannelData(0)), right = channels > 1 ? toInt16(buffer.getChannelData(1)) : left, chunks: Int8Array[] = [], block = 1152; for (let offset = 0; offset < left.length; offset += block) { const result = encoder.encodeBuffer(left.subarray(offset, offset + block), right.subarray(offset, offset + block)); if (result.length) chunks.push(result); if (offset % (block * 120) === 0) { onProgress(Math.round(offset / left.length * 100)); await new Promise<void>((resolve) => window.setTimeout(resolve, 0)); } } const final = encoder.flush(); if (final.length) chunks.push(final); onProgress(100); return new Blob(chunks.map((chunk) => chunk.buffer.slice(chunk.byteOffset, chunk.byteOffset + chunk.byteLength) as ArrayBuffer), { type:'audio/mpeg' }); }
function encodeWav(buffer: AudioBuffer): Blob { const channels = buffer.numberOfChannels, bytes = 44 + buffer.length * channels * 2, data = new ArrayBuffer(bytes), view = new DataView(data); const write = (offset: number, text: string) => { for (let index = 0; index < text.length; index += 1) view.setUint8(offset + index, text.charCodeAt(index)); }; write(0,'RIFF'); view.setUint32(4,bytes-8,true); write(8,'WAVE'); write(12,'fmt '); view.setUint32(16,16,true); view.setUint16(20,1,true); view.setUint16(22,channels,true); view.setUint32(24,buffer.sampleRate,true); view.setUint32(28,buffer.sampleRate*channels*2,true); view.setUint16(32,channels*2,true); view.setUint16(34,16,true); write(36,'data'); view.setUint32(40,bytes-44,true); const samples = Array.from({length:channels},(_,index) => buffer.getChannelData(index)); let offset=44; for(let frame=0;frame<buffer.length;frame+=1) for(let channel=0;channel<channels;channel+=1) { const value=Math.max(-1,Math.min(1,samples[channel][frame])); view.setInt16(offset,value<0?value*0x8000:value*0x7fff,true);offset+=2; } return new Blob([data],{type:'audio/wav'}); }
function toInt16(values: Float32Array): Int16Array { const result = new Int16Array(values.length); values.forEach((value,index) => { const sample=Math.max(-1,Math.min(1,value)); result[index]=sample<0?sample*0x8000:sample*0x7fff; }); return result; }
function formatBytes(bytes: number): string { if (!bytes) return '0 B'; const units=['B','KB','MB','GB'], index=Math.floor(Math.log(bytes)/Math.log(1024)); return `${(bytes/Math.pow(1024,index)).toFixed(2)} ${units[index]}`; }
function formatTime(seconds:number):string { const minutes=Math.floor(seconds/60), remaining=Math.floor(seconds%60); return `${String(minutes).padStart(2,'0')}:${String(remaining).padStart(2,'0')}`; }
function required<T extends Element>(root: ParentNode, selector:string):T { const element=root.querySelector<T>(selector); if(!element) throw new Error(`العنصر المطلوب غير موجود: ${selector}`); return element; }
