import { bootstrapStandaloneTool } from '@shared/ui/standalone-tool';
import { toolBySlug } from '@shared/tools';
import { iconSvg } from '@shared/ui/icons';
import { t } from '@shared/i18n';
import './background-remover.css';

type Snapshot = ImageData;
type WorkerMessage = { type:'progress'|'ready'|'done'|'error'; text?:string; mask?:ArrayBuffer; message?:string };

void bootstrapStandaloneTool('background-remover', (shell) => {
  if (!toolBySlug('background-remover')) throw new Error('تعذر العثور على تعريف أداة إزالة الخلفية.');
  shell.content.innerHTML = `
    <div class="imr-page">
      <header class="imr-header"><span class="imr-header-icon"><svg width="27" height="27" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path><circle cx="12" cy="12" r="4"></circle></svg></span><div><h1>${t('محرر الخلفية الشفاف')}</h1><p>${t('أزل الخلفية تلقائياً بالذكاء الاصطناعي أو صحّح الحواف محلياً بدقة.')}</p></div></header>
      <section class="imr-section"><p class="imr-section-label">${t('الصورة')}</p><label id="imr-drop" class="imr-card imr-drop-zone" for="imr-file"><span class="imr-drop-icon"><svg width="33" height="33" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg></span><b id="imr-drop-text">${t('اضغط هنا لرفع الصورة')}</b><span>PNG · JPG · WEBP</span><input id="imr-file" type="file" accept="image/*"></label></section>
      <main id="imr-editor" class="imr-editor" hidden>
        <section class="imr-section"><div class="imr-modes-row"><div class="imr-modes-btns"><button id="imr-erase" class="imr-mode-btn is-active" type="button"><span>${iconSvg('cutout','imr-mode-icon')}</span>${t('الممحاة')}</button><button id="imr-restore" class="imr-mode-btn" type="button"><span>${iconSvg('image','imr-mode-icon')}</span>${t('الاسترجاع')}</button><button id="imr-undo" class="imr-mode-btn imr-history" type="button" disabled title="${t('تراجع')}">${iconSvg('undo','imr-mode-icon')}</button><button id="imr-redo" class="imr-mode-btn imr-history" type="button" disabled title="${t('إعادة')}">${iconSvg('refresh','imr-mode-icon')}</button></div><button id="imr-ai" class="imr-ai-btn" type="button"><span class="imr-ai-star">${iconSvg('sparkles','imr-ai-icon')}</span><span id="imr-ai-text">${t('إزالة AI')}</span></button></div></section>
        <section class="imr-section"><div class="imr-canvas-wrap"><div class="imr-canvas-bg"><canvas id="imr-canvas"></canvas></div><div id="imr-zoom" class="imr-zoom" hidden><canvas id="imr-zoom-canvas" width="120" height="120"></canvas></div><div id="imr-ai-progress" class="imr-ai-progress" hidden><span class="imr-spinner"></span><span id="imr-ai-progress-text">${t('جاري التحضير…')}</span></div></div></section>
        <section class="imr-section"><div class="imr-card imr-brush-card"><div class="imr-ctrl-row"><span>${t('حجم الأداة')}</span><b id="imr-brush-value">45px</b></div><input id="imr-brush" class="imr-slider" type="range" min="5" max="150" value="45"><div class="imr-slider-marks"><span>5</span><span>40</span><span>80</span><span>120</span><span>150</span></div></div></section>
        <section class="imr-section"><button id="imr-download" class="imr-download" type="button"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg><span>${t('تنزيل الصورة (PNG شفاف)')}</span></button></section>
      </main>
    </div>`;
  const $ = <T extends Element>(selector:string) => required<T>(shell.content,selector);
  const file=$<HTMLInputElement>('#imr-file'), drop=$<HTMLElement>('#imr-drop'), dropText=$<HTMLElement>('#imr-drop-text'), editor=$<HTMLElement>('#imr-editor'), canvas=$<HTMLCanvasElement>('#imr-canvas'), canvasCtx=canvas.getContext('2d',{willReadFrequently:true}); if(!canvasCtx) throw new Error('Canvas غير متاح.'); const ctx:CanvasRenderingContext2D=canvasCtx; const original=document.createElement('canvas'), originalCtx=original.getContext('2d'); if(!originalCtx)throw new Error('تعذر تجهيز الصورة الأصلية.'); const erase=$<HTMLButtonElement>('#imr-erase'), restore=$<HTMLButtonElement>('#imr-restore'), undo=$<HTMLButtonElement>('#imr-undo'), redo=$<HTMLButtonElement>('#imr-redo'), ai=$<HTMLButtonElement>('#imr-ai'), aiText=$<HTMLElement>('#imr-ai-text'), brush=$<HTMLInputElement>('#imr-brush'), brushValue=$<HTMLElement>('#imr-brush-value'), download=$<HTMLButtonElement>('#imr-download'), zoom=$<HTMLElement>('#imr-zoom'), zoomCanvas=$<HTMLCanvasElement>('#imr-zoom-canvas'), zoomCandidate=zoomCanvas.getContext('2d'); if(!zoomCandidate) throw new Error('عدسة التكبير غير متاحة.'); const zoomCtx:CanvasRenderingContext2D=zoomCandidate; const progress=$<HTMLElement>('#imr-ai-progress'), progressText=$<HTMLElement>('#imr-ai-progress-text');
  let mode:'erase'|'restore'='erase', drawing=false, last:{x:number;y:number}|null=null, queuedPoint:ReturnType<typeof position>|null=null, paintFrame:number|null=null, filename='Arsenal_Transparent', undoStack:Snapshot[]=[], redoStack:Snapshot[]=[], worker:Worker|null=null, sourceReady=false;
  const MAX_HISTORY=5;
  const updateHistory=()=>{undo.disabled=undoStack.length===0;redo.disabled=redoStack.length===0;}; const updateBrush=()=>{brushValue.textContent=`${brush.value}px`;const percent=(Number(brush.value)-5)/145*100;brush.style.background=`linear-gradient(90deg,var(--accent-2) 0 ${percent}%,var(--surface-strong) ${percent}% 100%)`;}; const setMode=(next:'erase'|'restore')=>{mode=next;erase.classList.toggle('is-active',mode==='erase');restore.classList.toggle('is-active',mode==='restore');canvas.classList.toggle('is-restoring',mode==='restore');}; const saveSnapshot=()=>{undoStack.push(ctx.getImageData(0,0,canvas.width,canvas.height));if(undoStack.length>MAX_HISTORY)undoStack.shift();redoStack=[];updateHistory();};
  const position=(event:PointerEvent)=>{const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height,clientX:event.clientX,clientY:event.clientY,rect};};
  const updateZoom=(point:ReturnType<typeof position>)=>{zoom.hidden=false;zoomCtx.clearRect(0,0,120,120);zoomCtx.fillStyle='#111820';zoomCtx.fillRect(0,0,120,120);const size=Math.max(20,Number(brush.value)*1.6);zoomCtx.drawImage(canvas,point.x-size/2,point.y-size/2,size,size,0,0,120,120);zoomCtx.strokeStyle='#00d4aa';zoomCtx.lineWidth=1.5;zoomCtx.beginPath();zoomCtx.moveTo(60,42);zoomCtx.lineTo(60,78);zoomCtx.moveTo(42,60);zoomCtx.lineTo(78,60);zoomCtx.stroke();const relX=point.clientX-point.rect.left,relY=point.clientY-point.rect.top;zoom.style.left=relX>point.rect.width/2?'12px':'auto';zoom.style.right=relX>point.rect.width/2?'auto':'12px';zoom.style.top=relY>point.rect.height/2?'12px':'auto';zoom.style.bottom=relY>point.rect.height/2?'auto':'12px';};
  const renderPaint=()=>{paintFrame=null;if(!drawing||!last||!queuedPoint)return;const point=queuedPoint;queuedPoint=null;const size=Number(brush.value);ctx.save();if(mode==='erase'){ctx.globalCompositeOperation='destination-out';ctx.lineWidth=size;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(point.x,point.y);ctx.stroke();}else{const distance=Math.hypot(point.x-last.x,point.y-last.y),steps=Math.max(1,Math.ceil(distance/Math.max(2,size/2)));for(let step=0;step<=steps;step+=1){const t=step/steps,x=last.x+(point.x-last.x)*t,y=last.y+(point.y-last.y)*t;ctx.drawImage(original,x-size/2,y-size/2,size,size,x-size/2,y-size/2,size,size);}}ctx.restore();last=point;updateZoom(point);};
  const paint=(event:PointerEvent)=>{if(!drawing||!last)return;event.preventDefault();queuedPoint=position(event);if(paintFrame===null)paintFrame=requestAnimationFrame(renderPaint);};
  const stopPainting=()=>{if(paintFrame!==null){cancelAnimationFrame(paintFrame);paintFrame=null;}queuedPoint=null;drawing=false;last=null;zoom.hidden=true;};
  const load=async(selected:File)=>{drop.classList.add('is-loading');dropText.textContent=t('جاري فتح الصورة…');filename=selected.name.replace(/\.[^.]+$/,'')||filename;try{const image=await imageFromFile(selected);canvas.width=original.width=image.naturalWidth;canvas.height=original.height=image.naturalHeight;originalCtx.clearRect(0,0,original.width,original.height);originalCtx.drawImage(image,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0);undoStack=[];redoStack=[];sourceReady=true;editor.hidden=false;drop.classList.remove('is-loading');drop.classList.add('has-file');dropText.textContent=selected.name;updateHistory();updateBrush();shell.setStatus(t('الصورة جاهزة. يمكنك البدء بالممحاة أو الإزالة الذكية.'),'success');}catch(error){drop.classList.remove('is-loading');dropText.textContent=t('تعذر فتح الصورة');shell.setStatus(t('تعذر تحميل الصورة: {reason}', { reason: error instanceof Error ? error.message : t('خطأ غير متوقع') }),'error');}};
  file.addEventListener('change',()=>{const selected=file.files?.[0];if(selected)void load(selected);});['dragenter','dragover'].forEach((name)=>drop.addEventListener(name,(event)=>{event.preventDefault();drop.classList.add('drag-active');}));['dragleave','drop'].forEach((name)=>drop.addEventListener(name,(event)=>{event.preventDefault();drop.classList.remove('drag-active');}));drop.addEventListener('drop',(event)=>{const selected=event.dataTransfer?.files[0];if(selected?.type.startsWith('image/'))void load(selected);else shell.setStatus(t('اختر ملف صورة صالحاً فقط.'),'error');});
  erase.addEventListener('click',()=>setMode('erase'));restore.addEventListener('click',()=>setMode('restore'));brush.addEventListener('input',updateBrush);
  canvas.addEventListener('pointerdown',(event)=>{if(!sourceReady)return;try{canvas.setPointerCapture(event.pointerId);}catch{/* لا تتوفر في بعض الأحداث المركبة */}saveSnapshot();drawing=true;last=position(event);paint(event);});canvas.addEventListener('pointermove',paint);canvas.addEventListener('pointerup',stopPainting);canvas.addEventListener('pointercancel',stopPainting);window.addEventListener('pointerup',stopPainting);
  undo.addEventListener('click',()=>{const previous=undoStack.pop();if(!previous)return;redoStack.push(ctx.getImageData(0,0,canvas.width,canvas.height));if(redoStack.length>MAX_HISTORY)redoStack.shift();ctx.putImageData(previous,0,0);updateHistory();});redo.addEventListener('click',()=>{const following=redoStack.pop();if(!following)return;undoStack.push(ctx.getImageData(0,0,canvas.width,canvas.height));if(undoStack.length>MAX_HISTORY)undoStack.shift();ctx.putImageData(following,0,0);updateHistory();});
  const setProgress=(message:string,busy:boolean)=>{progress.hidden=!busy;progressText.textContent=message;ai.disabled=busy;aiText.textContent=busy?message:t('إزالة AI');}; const cleanWorker=()=>{worker?.terminate();worker=null;};
  ai.addEventListener('click',()=>{if(!sourceReady)return;saveSnapshot();cleanWorker();setProgress(t('جاري تحضير الذكاء الاصطناعي…'),true);shell.setStatus(t('تُحمّل مكتبات الذكاء الاصطناعي عند الطلب فقط.'));worker=new Worker(new URL('./worker.ts',import.meta.url),{type:'classic'});worker.onmessage=(event:MessageEvent<WorkerMessage>)=>{const message=event.data;if(message.type==='progress'){setProgress(message.text ? t(message.text) : t('جاري المعالجة…'),true);return;}if(message.type==='ready'){setProgress(t('جاري تحليل الصورة…'),true);const source=originalCtx.getImageData(0,0,original.width,original.height);worker?.postMessage({type:'run',payload:{data:source.data.buffer,width:original.width,height:original.height}},[source.data.buffer]);return;}if(message.type==='done'&&message.mask){applyMask(new Float32Array(message.mask));cleanWorker();setProgress(t('اكتملت إزالة الخلفية بنجاح'),false);shell.setStatus(t('اكتملت إزالة الخلفية محلياً. صحح الحواف بالفرشاة إذا احتجت.'),'success');return;}cleanWorker();setProgress(t('تعذر إكمال الإزالة'),false);shell.setStatus(t('فشلت إزالة الخلفية: {reason}', { reason: message.message || t('خطأ غير متوقع') }),'error');};worker.onerror=(event)=>{cleanWorker();setProgress(t('تعذر إكمال الإزالة'),false);shell.setStatus(t('تعذر تشغيل معالجة AI: {reason}', { reason: event.message || t('خطأ غير متوقع') }),'error');};worker.postMessage({type:'init'});});
  const applyMask=(mask:Float32Array)=>{const data=ctx.getImageData(0,0,canvas.width,canvas.height),size=1024;for(let index=0;index<canvas.width*canvas.height;index+=1){const x=index%canvas.width,y=Math.floor(index/canvas.width),mx=Math.min(size-1,Math.floor(x*size/canvas.width)),my=Math.min(size-1,Math.floor(y*size/canvas.height));data.data[index*4+3]=Math.round(Math.max(0,Math.min(1,mask[my*size+mx]))*255);}ctx.putImageData(data,0,0);};
  download.addEventListener('click',()=>canvas.toBlob((blob)=>{if(!blob)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${filename}_transparent.png`;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png'));
});
function required<T extends Element>(root:ParentNode,selector:string):T{const element=root.querySelector<T>(selector);if(!element)throw new Error(`العنصر المطلوب غير موجود: ${selector}`);return element;}function imageFromFile(file:File):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve(image);};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('صيغة الصورة غير مدعومة.'));};image.src=url;});}
